export const rawData=[
    // {
    //     "page_id": "19628662544",
    //     "url": "http://reddressboutique.com/products/so-divine-ivory-tweed-bag",
    //     "canonical_url": "https://www.reddress.com/products/so-divine-ivory-tweed-bag",
    //     "parent_url": "https://www.reddressboutique.com/collections/handbags-purses",
    //     "image_url": "http://cdn.shopify.com/s/files/1/1708/7943/products/4-5-2232819_1024x1024.jpg?v=1649191993",
    //     "price": "$5.00",
    //     "name": "Classy Ivory Tweed Bag - All Accessories | Red Dress",
    //     "product_confidence": "10",
    //     "crawled_time": "2022-04-13 14:06:51",
    //     "created_time": "2022-04-13 14:06:34",
    //     "width": null,
    //     "height": null,
    //     "issue": "[Errno 2] No such file or directory: 'data/test2.",
    //     "description": "This bag features a beige tweed purse, gold hardware, a pocket inside, and it comes with chain. \u2022 All Man Made Materials \u2022 Body of bag is 8\" x 6\" x 3\" \u2022 Chain is 11\"/22\" \u2022 Imported",
    //     "domain": "reddressboutique.com",
    //     "source": "DOMAIN",
    //     "brand": null,
    //     "slug": "classy-ivory-tweed-bag-all-accessories-red-dress-19628662544",
    //     "tags": "bag,chain,christian dior,christian dior pre,diamonte bow grab,dress,farfetch,lore lilac croc,mini,owned,philipp plein,quilted,red,red dress,shoulder,shoulder bag,tote,tote bag",
    //     "price_updated": null,
    //     "last_update": "2022-04-13 14:08:33",
    //     "currency": null,
    //     "price_old": null,
    //     "discount": null,
    //     "s3_url": null
    // },
    // {
    //     "page_id": "19628557341",
    //     "url": "http://reddressboutique.com/products/city-drives-silver-beaded-mesh-bag",
    //     "canonical_url": "https://www.reddress.com/products/city-drives-silver-beaded-mesh-bag",
    //     "parent_url": "http://reddressboutique.com/products/vividly-dreaming-light-wash-distressed-straight-jeans",
    //     "image_url": "http://cdn.shopify.com/s/files/1/1708/7943/products/4-12-2234853_1024x1024.jpg?v=1649796128",
    //     "price": "$5.00",
    //     "name": "Fancy Beaded Mesh Silver Bag - The Wedding Shop | Red Dress",
    //     "product_confidence": "10",
    //     "crawled_time": "2022-04-13 13:43:31",
    //     "created_time": "2022-04-13 13:43:11",
    //     "width": null,
    //     "height": null,
    //     "issue": "[Errno 2] No such file or directory: 'data/test2.",
    //     "description": "This bag features a silver rhinestone chain mesh bag with knot straps, silver accents, a strap that is removable, and a pocket inside. \u2022 All Man Made Materials \u2022 13\" x 6\" Bag \u2022 16\" Strap \u2022 Imported",
    //     "domain": "reddressboutique.com",
    //     "source": "DOMAIN",
    //     "brand": null,
    //     "slug": "fancy-beaded-mesh-silver-bag-the-wedding-shop-red-dress-19628557341",
    //     "tags": "back,back long sleeve,bikini,black,bra,crop,crop top,fancy beaded mesh,farfetch,free people,hunza g,long,long sleeve,loop lace back,mura boutique,revolve,sleeve,top",
    //     "price_updated": null,
    //     "last_update": "2022-04-13 13:44:58",
    //     "currency": null,
    //     "price_old": null,
    //     "discount": null,
    //     "s3_url": null
    // },
    // {
    //     "page_id": "19626443832",
    //     "url": "http://surfstitch.com/roxy-roxy-board-sleeve-bag-true-black-pensine-erjba03061-kvj6.html",
    //     "canonical_url": "https://www.surfstitch.com/roxy-roxy-board-sleeve-bag-true-black-pensine-erjba03061-kvj6.html",
    //     "parent_url": "https://www.surfstitch.com/snow/outerwear/womens",
    //     "image_url": "https://www.surfstitch.com/dw/image/v2/BBCN_PRD/on/demandware.static/-/Sites-ss-master-catalog/default/dwbcb38556/images/ERJBA03061-KVJ6/TRUE-BLACK-PENSINE-BOARDSPORTS-SNOW-ROXY-WOMENS-ERJBA03061-KVJ6_1.JPG?sw=220&sh=275&sm=fit",
    //     "price": "$139.99",
    //     "name": "Roxy Roxy Board Sleeve Bag - True Black Pensine | SurfStitch",
    //     "product_confidence": "10",
    //     "crawled_time": "2022-04-13 09:41:55",
    //     "created_time": "2022-04-13 09:40:39",
    //     "width": null,
    //     "height": null,
    //     "issue": "[Errno 2] No such file or directory: 'data/test2.",
    //     "description": "Buy True Black Pensine Roxy Roxy Board Sleeve Bag Online From Surfstitch & More Roxy Accessories. Shipping available Australia wide including Sydney, Melbourne, Brisbane, Adelaide, Perth, Hobart & Darwin",
    //     "domain": "surfstitch.com",
    //     "source": "PARENT_URL",
    //     "brand": null,
    //     "slug": "roxy-roxy-board-sleeve-bag-true-black-pensine-surfstitch-19626443832",
    //     "tags": "37 inch longboard,bag,black,complete,cruiser,face mask,farfetch,floral,inch,inch longboard,island 32inch fish,longboard,natasha zinko,print,print silk,surfstitch,true black,true black pensine",
    //     "price_updated": null,
    //     "last_update": "2022-04-13 09:45:07",
    //     "currency": null,
    //     "price_old": null,
    //     "discount": null,
    //     "s3_url": null
    // },
    // {
    //     "page_id": "19625845910",
    //     "url": "http://fwrd.com/product-jacquemus-le-polo-bagnu/JQUF-WS188/?d=Womens&itrownum=3&itcurrpage=1&itview=05",
    //     "canonical_url": "https://www.fwrd.com/product-jacquemus-le-polo-bagnu-in-blue-stripes/JQUF-WS188/",
    //     "parent_url": "https://www.fwrd.com/brand-jacquemus/cee93a/?navsrc=clothing",
    //     "image_url": "https://is4.fwrdassets.com/images/p/fw/p/JQUF-WS188_V1.jpg",
    //     "price": "$370",
    //     "name": "JACQUEMUS Le Polo Bagnu in Blue Stripes | FWRD",
    //     "product_confidence": "10",
    //     "crawled_time": "2022-04-13 08:09:42",
    //     "created_time": "2022-04-13 08:09:06",
    //     "width": null,
    //     "height": null,
    //     "issue": "[Errno 2] No such file or directory: 'data/test2.",
    //     "description": "Shop for JACQUEMUS Le Polo Bagnu in Blue Stripes at FWRD. Free 2 day shipping and returns.",
    //     "domain": "fwrd.com",
    //     "source": "PARENT_URL",
    //     "brand": null,
    //     "slug": "jacquemus-le-polo-bagnu-in-blue-stripes-fwrd-19625845910",
    //     "tags": "boutique,crop,crop top,crop top priceless,detail,dress,free people,fwrd,jacquemus le polo,long sleeve,mura boutique,playsuit,sleeve,sleeve crop top,tie,top,v neck,white",
    //     "price_updated": null,
    //     "last_update": "2022-04-13 08:11:55",
    //     "currency": null,
    //     "price_old": null,
    //     "discount": null,
    //     "s3_url": null
    // },
    {
        "page_id": "19625446167",
        "url": "http://therealreal.com/products/women/shoes/boots/gucci-guccissima-nylon-boots-d26he",
        "canonical_url": "https://www.therealreal.com/products/women/shoes/boots/gucci-guccissima-nylon-boots-d26he",
        "parent_url": "http://www.therealreal.com/shop/women/shoes/boots",
        "image_url": "https://product-images.therealreal.com/GUC904758_1_enlarged.jpg",
        "price": "$845.00",
        "name": "Gucci Guccissima Nylon Boots - Black Boots, Shoes - GUC904758 | The RealReal",
        "product_confidence": "8",
        "crawled_time": "2022-04-13 07:22:19",
        "created_time": "2022-04-13 07:21:49",
        "width": null,
        "height": null,
        "issue": "HTTP Error 403: Forbidden",
        "description": "<ul><li>Gucci Ankle Boots</li><li>By Alessandro Michele</li><li>Black</li><li>Guccissima Nylon</li><li>Round-Toes</li><li>Block Heels with Platform</li><li>Lace-Up Closure at Ankles</li><li>Includes Box & Dust Bag</li></ul><p><strong>Fit:</strong> This style typically runs a half size small.</p>",
        "domain": "therealreal.com",
        "source": "PARENT_URL",
        "brand": null,
        "slug": "gucci-guccissima-nylon-boots-black-boots-shoes-guc904758-the-realreal-19625446167",
        "tags": "ankle,ankle boots,boots,chunky,detail,dr martens,farfetch,lace,leather,shoes,sole,up,up ankle,up ankle boots,up boots,up derby shoes,up leather boots,up shoes",
        "price_updated": null,
        "last_update": "2022-04-13 08:16:57",
        "currency": null,
        "price_old": null,
        "discount": null,
        "s3_url": null
    },
    {
        "page_id": "19625446149",
        "url": "http://therealreal.com/products/women/shoes/boots/christian-louboutin-suede-boots-d7tp3",
        "canonical_url": "https://www.therealreal.com/products/women/shoes/boots/christian-louboutin-suede-boots-d7tp3",
        "parent_url": "http://www.therealreal.com/shop/women/shoes/boots",
        "image_url": "https://product-images.therealreal.com/CHT245003_1_enlarged.jpg",
        "price": "$495.00",
        "name": "Christian Louboutin Suede Boots - Red Boots, Shoes - CHT245003 | The RealReal",
        "product_confidence": "8",
        "crawled_time": "2022-04-13 07:22:26",
        "created_time": "2022-04-13 07:21:49",
        "width": null,
        "height": null,
        "issue": "HTTP Error 403: Forbidden",
        "description": "<ul><li>Christian Louboutin Suede Ankle Boots</li><li>Red</li><li>Pointed-Toes</li><li>Block Heels with Platform</li><li>Exposed Zip Closure at Sides</li><li>Includes Dust Bag</li></ul><p><strong>Designer Fit:</strong> This style typically runs a full size small. </p>",
        "domain": "therealreal.com",
        "source": "PARENT_URL",
        "brand": null,
        "slug": "christian-louboutin-suede-boots-red-boots-shoes-cht245003-the-realreal-19625446149",
        "tags": "85mm ankle boots,ankle,ankle boots,black,block,boots,detail ankle boots,farfetch,gianvito,gianvito rossi,giuseppe zanotti,heel,heel ankle,heel ankle boots,leather,rossi,stuart weitzman,suede",
        "price_updated": null,
        "last_update": "2022-04-13 08:17:18",
        "currency": null,
        "price_old": null,
        "discount": null,
        "s3_url": null
    },
    {
        "page_id": "19625446138",
        "url": "http://therealreal.com/products/women/shoes/boots/rag-bone-suede-boots-d3ned",
        "canonical_url": "https://www.therealreal.com/products/women/shoes/boots/rag-bone-suede-boots-d3ned",
        "parent_url": "http://www.therealreal.com/shop/women/shoes/boots",
        "image_url": "https://product-images.therealreal.com/WRAGB389428_1_enlarged.jpg",
        "price": "$165.00",
        "name": "Rag & Bone Suede Boots - Neutrals Boots, Shoes - WRAGB389428 | The RealReal",
        "product_confidence": "8",
        "crawled_time": "2022-04-13 07:22:49",
        "created_time": "2022-04-13 07:21:49",
        "width": null,
        "height": null,
        "issue": "HTTP Error 403: Forbidden",
        "description": "<ul><li>Rag & Bone Suede Ankle Boots</li><li>Neutrals</li><li>Round-Toes</li><li>Block Heels</li><li>Wrap-Around Straps</li><li>Includes Box & Dust Bag</li></ul><p><strong>Designer Fit:</strong> Boots by Rag & Bone typically run a half size small.</p>",
        "domain": "therealreal.com",
        "source": "PARENT_URL",
        "brand": null,
        "slug": "rag-bone-suede-boots-neutrals-boots-shoes-wragb389428-the-realreal-19625446138",
        "tags": "ankle,ankle boots,boot,boots,creative,farfetch,heel,heel ankle,heel ankle boots,leather,officine,officine creative,revolve,see chlo\u00e9,simon miller high,stuart weitzman,suede,toe ankle boots",
        "price_updated": null,
        "last_update": "2022-04-13 08:18:09",
        "currency": null,
        "price_old": null,
        "discount": null,
        "s3_url": null
    },
    {
        "page_id": "19625446136",
        "url": "http://therealreal.com/products/women/shoes/boots/stuart-weitzman-suede-boots-d8her",
        "canonical_url": "https://www.therealreal.com/products/women/shoes/boots/stuart-weitzman-suede-boots-d8her",
        "parent_url": "http://www.therealreal.com/shop/women/shoes/boots",
        "image_url": "https://product-images.therealreal.com/WSU198931_1_enlarged.jpg",
        "price": "$275.00",
        "name": "Stuart Weitzman Suede Boots - Black Boots, Shoes - WSU198931 | The RealReal",
        "product_confidence": "8",
        "crawled_time": "2022-04-13 07:22:56",
        "created_time": "2022-04-13 07:21:49",
        "width": null,
        "height": null,
        "issue": "HTTP Error 403: Forbidden",
        "description": "<ul><li>Stuart Weitzman Suede Over-The-Knee Boots</li><li>Black</li><li>Round-Toes</li><li>Tie Closures</li><li>Includes Box & Dust Bag</li></ul><p><strong>Designer Fit:</strong> This designer typically runs true to size.</p>",
        "domain": "therealreal.com",
        "source": "PARENT_URL",
        "brand": null,
        "slug": "stuart-weitzman-suede-boots-black-boots-shoes-wsu198931-the-realreal-19625446136",
        "tags": "black,boots,farfetch,high,high boots,high leather boots,high suede boots,knee,knee boots,length boots,over,rick owens,stuart,stuart weitzman,stuart weitzman lowl,the,thigh,weitzman",
        "price_updated": null,
        "last_update": "2022-04-13 08:18:23",
        "currency": null,
        "price_old": null,
        "discount": null,
        "s3_url": null
    },
    {
        "page_id": "19625446097",
        "url": "http://therealreal.com/products/women/shoes/boots/saint-laurent-sock-boots-d8jua",
        "canonical_url": "https://www.therealreal.com/products/women/shoes/boots/saint-laurent-sock-boots-d8jua",
        "parent_url": "http://www.therealreal.com/shop/women/shoes/boots",
        "image_url": "https://product-images.therealreal.com/SNT175747_1_enlarged.jpg",
        "price": "$395.00",
        "name": "Saint Laurent Sock Boots - Black Boots, Shoes - SNT175747 | The RealReal",
        "product_confidence": "8",
        "crawled_time": "2022-04-13 07:23:25",
        "created_time": "2022-04-13 07:21:49",
        "width": null,
        "height": null,
        "issue": "HTTP Error 403: Forbidden",
        "description": "<ul><li>Saint Laurent Mid-Calf Sock Boots</li><li>Black</li><li>Semi-Pointed Toes</li><li>Block Heels</li><li>Exposed Zip Closure at Sides</li><li>Includes Dust Bag</li></ul><p><strong>Fit:</strong> This style typically runs a half size small.</p>",
        "domain": "therealreal.com",
        "source": "PARENT_URL",
        "brand": null,
        "slug": "saint-laurent-sock-boots-black-boots-shoes-snt175747-the-realreal-19625446097",
        "tags": "ankle,ankle boots,black,block,boots,farfetch,heel,heel ankle,heel ankle boots,leather,maison margiela,maison margiela tabi,revolve,saint laurent,stuart,stuart weitzman,suede,toe ankle boots",
        "price_updated": null,
        "last_update": "2022-04-13 08:19:27",
        "currency": null,
        "price_old": null,
        "discount": null,
        "s3_url": null
    },
    {
        "page_id": "19625446069",
        "url": "http://therealreal.com/products/women/shoes/boots/golden-goose-patent-leather-graphic-print-western-boots-d7mk7",
        "canonical_url": "https://www.therealreal.com/products/women/shoes/boots/golden-goose-patent-leather-graphic-print-western-boots-d7mk7",
        "parent_url": "http://www.therealreal.com/shop/women/shoes/boots",
        "image_url": "https://product-images.therealreal.com/WG568789_1_enlarged.jpg",
        "price": "$325.00",
        "name": "Golden Goose Patent Leather Graphic Print Western Boots - Black Boots, Shoes - WG568789 | The RealR",
        "product_confidence": "8",
        "crawled_time": "2022-04-13 07:23:37",
        "created_time": "2022-04-13 07:21:49",
        "width": null,
        "height": null,
        "issue": "HTTP Error 403: Forbidden",
        "description": "<ul><li>Golden Goose Patent Leather Ankle Western Boots</li><li>Black</li><li>Graphic Print</li><li>Square-Toes with Studded Accents</li><li>Block Heels</li><li>Wrap-Around Straps & Exposed Zip Closure at Sides</li><li>Includes Box, Dust Bag & Additional Embellishments</li></ul><p><strong>Designer Fit:</strong> This designer typically runs true to size.</p>",
        "domain": "therealreal.com",
        "source": "PARENT_URL",
        "brand": null,
        "slug": "golden-goose-patent-leather-graphic-print-western-boots-black-boots-shoes-wg568789-the-realr-19625446069",
        "tags": "amiri bandana boot,ankle,ankle boots,black,boot,boot black,boots,buckle,detail,dr martens,farfetch,lace,leather,stud ankle boots,up,up ankle,up ankle boots,up boots",
        "price_updated": null,
        "last_update": "2022-04-13 08:20:07",
        "currency": null,
        "price_old": null,
        "discount": null,
        "s3_url": null
    },
    {
        "page_id": "19625446054",
        "url": "http://therealreal.com/products/women/shoes/boots/alexandre-vauthier-satin-boots-d6umu",
        "canonical_url": "https://www.therealreal.com/products/women/shoes/boots/alexandre-vauthier-satin-boots-d6umu",
        "parent_url": "http://www.therealreal.com/shop/women/shoes/boots",
        "image_url": "https://product-images.therealreal.com/AVR22244_1_enlarged.jpg",
        "price": "$625.00",
        "name": "Alexandre Vauthier Satin Boots - Black Boots, Shoes - AVR22244 | The RealReal",
        "product_confidence": "8",
        "crawled_time": "2022-04-13 07:23:49",
        "created_time": "2022-04-13 07:21:49",
        "width": null,
        "height": null,
        "issue": "HTTP Error 403: Forbidden",
        "description": "<ul><li>Alexandre Vauthier Satin Ankle Boots</li><li>Black</li><li>Pointed-Toes</li><li>Stiletto Heels</li><li>Includes Box & Dust Bag</li></ul>",
        "domain": "therealreal.com",
        "source": "PARENT_URL",
        "brand": null,
        "slug": "alexandre-vauthier-satin-boots-black-boots-shoes-avr22244-the-realreal-19625446054",
        "tags": "ankle,ankle boots,black,boot,bootie,bootie black,boots,farfetch,giuseppe zanotti,leather ankle boots,maison margiela tabi,pointed,revolve,stuart weitzman,suede,toe,toe ankle,toe ankle boots",
        "price_updated": null,
        "last_update": "2022-04-13 08:20:28",
        "currency": null,
        "price_old": null,
        "discount": null,
        "s3_url": null
    },
    {
        "page_id": "19625446052",
        "url": "http://therealreal.com/products/women/shoes/boots/chanel-2019-interlocking-cc-logo-riding-boots-w-tags-d6pyb",
        "canonical_url": "https://www.therealreal.com/products/women/shoes/boots/chanel-2019-interlocking-cc-logo-riding-boots-w-tags-d6pyb",
        "parent_url": "http://www.therealreal.com/shop/women/shoes/boots",
        "image_url": "https://product-images.therealreal.com/CHA698542_1_enlarged.jpg",
        "price": "$1595.00",
        "name": "Chanel 2019 Interlocking CC Logo Riding Boots w/ Tags - Black Boots, Shoes - CHA698542 | The RealRe",
        "product_confidence": "8",
        "crawled_time": "2022-04-13 07:23:56",
        "created_time": "2022-04-13 07:21:49",
        "width": null,
        "height": null,
        "issue": "HTTP Error 403: Forbidden",
        "description": "<ul><li>Chanel Velvet Knee-High Riding Boots</li><li>From the 2019 Collection</li><li>Black</li><li>Interlocking CC Logo & Chain-Link Accent</li><li>Patent Leather Trim</li><li>Semi-Pointed Toes with Chain-Link Accents</li><li>Block Heels</li><li>Wrap-Around Straps</li><li>Includes Box & Dust Bag</li></ul><p><strong>Fit:</strong> This style typically runs a full size small.</p>",
        "domain": "therealreal.com",
        "source": "PARENT_URL",
        "brand": null,
        "slug": "chanel-2019-interlocking-cc-logo-riding-boots-w-tags-black-boots-shoes-cha698542-the-realre-19625446052",
        "tags": "alberta ferretti,ankle,black,black boots shoes,boot,boots,farfetch,heel,high,high boots,knee,leather,leather boots,length,length boots,on boots,pennsylvania shoe sp,up leather boots",
        "price_updated": null,
        "last_update": "2022-04-13 08:20:49",
        "currency": null,
        "price_old": null,
        "discount": null,
        "s3_url": null
    },
    {
        "page_id": "19625446046",
        "url": "http://therealreal.com/products/women/shoes/boots/chanel-leather-sock-boots-d5y3g",
        "canonical_url": "https://www.therealreal.com/products/women/shoes/boots/chanel-leather-sock-boots-d5y3g",
        "parent_url": "http://www.therealreal.com/shop/women/shoes/boots",
        "image_url": "https://product-images.therealreal.com/CHA697740_1_enlarged.jpg",
        "price": "$575.00",
        "name": "Chanel Leather Sock Boots - Brown Boots, Shoes - CHA697740 | The RealReal",
        "product_confidence": "8",
        "crawled_time": "2022-04-13 07:24:01",
        "created_time": "2022-04-13 07:21:49",
        "width": null,
        "height": null,
        "issue": "HTTP Error 403: Forbidden",
        "description": "<ul><li>Chanel Leather Knee-High Sock Boots</li><li>Brown</li><li>Semi-Pointed Toes</li><li>Block Heels</li><li>Includes Dust Bag</li></ul><p><strong>Fit:</strong> This style typically runs a full size small.</p>",
        "domain": "therealreal.com",
        "source": "PARENT_URL",
        "brand": null,
        "slug": "chanel-leather-sock-boots-brown-boots-shoes-cha697740-the-realreal-19625446046",
        "tags": "black,boots,farfetch,high,high boots,high leather boots,knee,knee boots,leather,length,length boots,length leather,length leather boots,pointed,stuart,stuart weitzman,stuart weitzman knee,weitzman",
        "price_updated": null,
        "last_update": "2022-04-13 08:21:10",
        "currency": null,
        "price_old": null,
        "discount": null,
        "s3_url": null
    },
    {
        "page_id": "19625446022",
        "url": "http://therealreal.com/products/women/shoes/boots/gucci-interlocking-g-logo-leather-boots-w-tags-d66je",
        "canonical_url": "https://www.therealreal.com/products/women/shoes/boots/gucci-interlocking-g-logo-leather-boots-w-tags-d66je",
        "parent_url": "http://www.therealreal.com/shop/women/shoes/boots",
        "image_url": "https://product-images.therealreal.com/GUC912782_1_enlarged.jpg",
        "price": "$795.00",
        "name": "Gucci Interlocking G Logo Leather Boots w/ Tags - Black Boots, Shoes - GUC912782 | The RealReal",
        "product_confidence": "8",
        "crawled_time": "2022-04-13 07:24:36",
        "created_time": "2022-04-13 07:21:49",
        "width": null,
        "height": null,
        "issue": "HTTP Error 403: Forbidden",
        "description": "<ul><li>Gucci Leather Ankle Boots</li><li>Black</li><li>Interlocking G Logo</li><li>Pointed-Toes</li><li>Kitten Heels</li><li>Concealed Zip Closure at Sides</li><li>Includes Box & Dust Bag</li></ul><p><strong>Fit:</strong> This style typically runs a half size small.</p>",
        "domain": "therealreal.com",
        "source": "PARENT_URL",
        "brand": null,
        "slug": "gucci-interlocking-g-logo-leather-boots-w-tags-black-boots-shoes-guc912782-the-realreal-19625446022",
        "tags": "ankle,ankle boots,black,black suede,black suede studio,bootie,boots,farfetch,heel,heel ankle,heel ankle boots,leather,paris texas,pointed,revolve,toe,toe ankle,toe ankle boots",
        "price_updated": null,
        "last_update": "2022-04-13 08:22:28",
        "currency": null,
        "price_old": null,
        "discount": null,
        "s3_url": null
    },
    {
        "page_id": "19625446013",
        "url": "http://therealreal.com/products/women/shoes/boots/christian-louboutin-leather-lace-up-boots-d7qv0",
        "canonical_url": "https://www.therealreal.com/products/women/shoes/boots/christian-louboutin-leather-lace-up-boots-d7qv0",
        "parent_url": "http://www.therealreal.com/shop/women/shoes/boots",
        "image_url": "https://product-images.therealreal.com/CHT244949_1_enlarged.jpg",
        "price": "$525.00",
        "name": "Christian Louboutin Leather Lace-Up Boots - Black Boots, Shoes - CHT244949 | The RealReal",
        "product_confidence": "8",
        "crawled_time": "2022-04-13 07:24:49",
        "created_time": "2022-04-13 07:21:49",
        "width": null,
        "height": null,
        "issue": "HTTP Error 403: Forbidden",
        "description": "<ul><li>Christian Louboutin Leather Ankle Lace-Up Boots</li><li>Black</li><li>Square-Toes</li><li>Stiletto Heels with Platform</li><li>Multistrap & Exposed Zip Closure at Ankles</li><li>Includes Box & Dust Bag</li></ul><p><strong>Designer Fit:</strong> This style typically runs a full size small. </p>",
        "domain": "therealreal.com",
        "source": "PARENT_URL",
        "brand": null,
        "slug": "christian-louboutin-leather-laceup-boots-black-boots-shoes-cht244949-the-realreal-19625446013",
        "tags": "ankle,ankle boots,black,boot,bootie,boots,farfetch,giuseppe zanotti,lace,leather,revolve,up,up ankle,up ankle boots,up boots,up leather boots,valentino garavani,valentino garavani r",
        "price_updated": null,
        "last_update": "2022-04-13 08:23:09",
        "currency": null,
        "price_old": null,
        "discount": null,
        "s3_url": null
    },
    {
        "page_id": "19625446000",
        "url": "http://therealreal.com/products/women/shoes/boots/balmain-peep-toe-leather-boots-d79v4",
        "canonical_url": "https://www.therealreal.com/products/women/shoes/boots/balmain-peep-toe-leather-boots-d79v4",
        "parent_url": "http://www.therealreal.com/shop/women/shoes/boots",
        "image_url": "https://product-images.therealreal.com/BAM56837_1_enlarged.jpg",
        "price": "$525.00",
        "name": "Balmain Peep Toe Leather Boots - Black Boots, Shoes - BAM56837 | The RealReal",
        "product_confidence": "8",
        "crawled_time": "2022-04-13 07:25:02",
        "created_time": "2022-04-13 07:21:49",
        "width": null,
        "height": null,
        "issue": "HTTP Error 403: Forbidden",
        "description": "<ul><li>Balmain Peep Toe Over-The-Knee Boots</li><li>Black Leather</li><li>Semi-Pointed Toes with Chain-Link Accents</li><li>Block Heels with Platform</li><li>Includes Box & Dust Bag</li></ul>",
        "domain": "therealreal.com",
        "source": "PARENT_URL",
        "brand": null,
        "slug": "balmain-peep-toe-leather-boots-black-boots-shoes-bam56837-the-realreal-19625446000",
        "tags": "amina muaddi,amina muaddi olivia,black,boots,farfetch,gia borghini x,high,high boots,high leather boots,knee,knee boots,leather,length,length boots,over,stuart weitzman,the,thigh",
        "price_updated": null,
        "last_update": "2022-04-13 08:23:41",
        "currency": null,
        "price_old": null,
        "discount": null,
        "s3_url": null
    },
    {
        "page_id": "19625445986",
        "url": "http://therealreal.com/products/women/shoes/boots/the-row-leather-rain-boots-w-tags-d7ob8",
        "canonical_url": "https://www.therealreal.com/products/women/shoes/boots/the-row-leather-rain-boots-w-tags-d7ob8",
        "parent_url": "http://www.therealreal.com/shop/women/shoes/boots",
        "image_url": "https://product-images.therealreal.com/THR94366_1_enlarged.jpg",
        "price": "$1295.00",
        "name": "The Row Leather Rain Boots w/ Tags - Black Boots, Shoes - THR94366 | The RealReal",
        "product_confidence": "8",
        "crawled_time": "2022-04-13 07:25:15",
        "created_time": "2022-04-13 07:21:49",
        "width": null,
        "height": null,
        "issue": "HTTP Error 403: Forbidden",
        "description": "<ul><li>The Row Leather Mid-Calf Rain Boots</li><li>Black & Brown</li><li>Square-Toes</li><li>Block Heels</li><li>Concealed Zip Closure at Ankles</li><li>Includes Box & Dust Bag</li></ul>",
        "domain": "therealreal.com",
        "source": "PARENT_URL",
        "brand": null,
        "slug": "the-row-leather-rain-boots-w-tags-black-boots-shoes-thr94366-the-realreal-19625445986",
        "tags": "black,boots,farfetch,heel,high,high boots,high leather,high leather boots,knee,leather,leather boots,length,length boots,stuart,stuart weitzman,stuart weitzman knee,via roma 15,weitzman",
        "price_updated": null,
        "last_update": "2022-04-13 08:24:13",
        "currency": null,
        "price_old": null,
        "discount": null,
        "s3_url": null
    },
    {
        "page_id": "19625445984",
        "url": "http://therealreal.com/products/women/shoes/boots/dries-van-noten-embossed-leather-boots-d8gmh",
        "canonical_url": "https://www.therealreal.com/products/women/shoes/boots/dries-van-noten-embossed-leather-boots-d8gmh",
        "parent_url": "http://www.therealreal.com/shop/women/shoes/boots",
        "image_url": "https://product-images.therealreal.com/DRI105222_1_enlarged.jpg",
        "price": "$345.00",
        "name": "Dries Van Noten Embossed Leather Boots - Neutrals Boots, Shoes - DRI105222 | The RealReal",
        "product_confidence": "8",
        "crawled_time": "2022-04-13 07:25:22",
        "created_time": "2022-04-13 07:21:49",
        "width": null,
        "height": null,
        "issue": "HTTP Error 403: Forbidden",
        "description": "<ul><li>Dries Van Noten Embossed Mid-Calf Boots</li><li>Neutrals Leather</li><li>Animal Print</li><li>Round-Toes</li><li>Block Heels</li><li>Exposed Zip Closure at Sides</li><li>Includes Dust Bag</li></ul><p><strong>Designer Fit:</strong> Boots by Dries Van Noten typically run a half size small.</p>",
        "domain": "therealreal.com",
        "source": "PARENT_URL",
        "brand": null,
        "slug": "dries-van-noten-embossed-leather-boots-neutrals-boots-shoes-dri105222-the-realreal-19625445984",
        "tags": "ankle,ankle boots,black,boot,boots,farfetch,giuseppe zanotti,heel,heel ankle,heel ankle boots,heel boots,lace,platform,revolve,simon miller high,up,up ankle,up ankle boots",
        "price_updated": null,
        "last_update": "2022-04-13 08:24:23",
        "currency": null,
        "price_old": null,
        "discount": null,
        "s3_url": null
    },
    {
        "page_id": "19625445974",
        "url": "http://therealreal.com/products/women/shoes/boots/burberry-horse-clip-bridle-leather-riding-boots-w-tags-d57hw",
        "canonical_url": "https://www.therealreal.com/products/women/shoes/boots/burberry-horse-clip-bridle-leather-riding-boots-w-tags-d57hw",
        "parent_url": "http://www.therealreal.com/shop/women/shoes/boots",
        "image_url": "https://product-images.therealreal.com/BUR271919_1_enlarged.jpg",
        "price": "$625.00",
        "name": "Burberry Horse Clip Bridle Leather Riding Boots w/ Tags - Black Boots, Shoes - BUR271919 | The Real",
        "product_confidence": "8",
        "crawled_time": "2022-04-13 07:25:27",
        "created_time": "2022-04-13 07:21:49",
        "width": null,
        "height": null,
        "issue": "HTTP Error 403: Forbidden",
        "description": "<ul><li>Burberry Horse Clip Bridle Knee-High Riding Boots</li><li>Black Leather</li><li>Round-Toes</li><li>Wrap-Around Straps</li><li>Includes Box & Dust Bag</li></ul><p><strong>Designer Fit:</strong> Boots by Burberry typically run a half size small.</p>",
        "domain": "therealreal.com",
        "source": "PARENT_URL",
        "brand": null,
        "slug": "burberry-horse-clip-bridle-leather-riding-boots-w-tags-black-boots-shoes-bur271919-the-real-19625445974",
        "tags": "5050 lift,black,boot,boots,bottega veneta,farfetch,high,high boots,high leather boots,knee,leather,length,length boots,length leather boots,stuart,stuart weitzman,stuart weitzman 5050,weitzman",
        "price_updated": null,
        "last_update": "2022-04-13 08:24:35",
        "currency": null,
        "price_old": null,
        "discount": null,
        "s3_url": null
    },
    {
        "page_id": "19625445893",
        "url": "http://therealreal.com/products/women/shoes/boots/burberry-leather-mesh-accents-chelsea-boots-d8ldg",
        "canonical_url": "https://www.therealreal.com/products/women/shoes/boots/burberry-leather-mesh-accents-chelsea-boots-d8ldg",
        "parent_url": "http://www.therealreal.com/shop/women/shoes/boots",
        "image_url": "https://product-images.therealreal.com/BUR270769_1_enlarged.jpg",
        "price": "$245.00",
        "name": "Burberry Leather Mesh Accents Chelsea Boots - Brown Boots, Shoes - BUR270769 | The RealReal",
        "product_confidence": "8",
        "crawled_time": "2022-04-13 07:26:05",
        "created_time": "2022-04-13 07:21:49",
        "width": null,
        "height": null,
        "issue": "HTTP Error 403: Forbidden",
        "description": "<ul><li>Burberry Leather Ankle Chelsea Boots</li><li>Brown</li><li>Semi-Pointed Toes with Mesh Accents</li><li>Block Heels</li><li>Includes Box & Dust Bag</li></ul><p><strong>Designer Fit:</strong> Boots by Burberry typically run a half size small.</p>",
        "domain": "therealreal.com",
        "source": "PARENT_URL",
        "brand": null,
        "slug": "burberry-leather-mesh-accents-chelsea-boots-brown-boots-shoes-bur270769-the-realreal-19625445893",
        "tags": "ankle,ankle boots,boot,boots,chelsea,chelsea ankle,chelsea boots,elasticated,farfetch,leather,on,on leather,on leather boots,scarosso elena chels,slip,toe,toe ankle,toe ankle boots",
        "price_updated": null,
        "last_update": "2022-04-13 08:26:09",
        "currency": null,
        "price_old": null,
        "discount": null,
        "s3_url": null
    },
    {
        "page_id": "19625445874",
        "url": "http://therealreal.com/products/women/shoes/boots/prada-suede-boots-d2y14",
        "canonical_url": "https://www.therealreal.com/products/women/shoes/boots/prada-suede-boots-d2y14",
        "parent_url": "http://www.therealreal.com/shop/women/shoes/boots",
        "image_url": "https://product-images.therealreal.com/PRA640100_1_enlarged.jpg",
        "price": "$345.00",
        "name": "Prada Suede Boots - Black Boots, Shoes - PRA640100 | The RealReal",
        "product_confidence": "8",
        "crawled_time": "2022-04-13 07:26:24",
        "created_time": "2022-04-13 07:21:48",
        "width": null,
        "height": null,
        "issue": "HTTP Error 403: Forbidden",
        "description": "<ul><li>Prada Suede Knee-High Boots</li><li>Black</li><li>Semi-Pointed Toes</li><li>Block Heels</li><li>Includes Dust Bag</li></ul><p><strong>Fit:</strong> This style typically runs a half size small.</p>",
        "domain": "therealreal.com",
        "source": "PARENT_URL",
        "brand": null,
        "slug": "prada-suede-boots-black-boots-shoes-pra640100-the-realreal-19625445874",
        "tags": "black,boots,farfetch,high,high boots,high suede boots,knee,knee boots,leather,leather boots,length,length boots,stuart,stuart weitzman,stuart weitzman 5050,stuart weitzman knee,suede,weitzman",
        "price_updated": null,
        "last_update": "2022-04-13 08:26:50",
        "currency": null,
        "price_old": null,
        "discount": null,
        "s3_url": null
    },
    {
        "page_id": "19625445805",
        "url": "http://therealreal.com/products/women/shoes/boots/saint-laurent-leather-moto-boots-d7x1f",
        "canonical_url": "https://www.therealreal.com/products/women/shoes/boots/saint-laurent-leather-moto-boots-d7x1f",
        "parent_url": "http://www.therealreal.com/shop/women/shoes/boots",
        "image_url": "https://product-images.therealreal.com/SNT175465_1_enlarged.jpg",
        "price": "$525.00",
        "name": "Saint Laurent Leather Moto Boots - Black Boots, Shoes - SNT175465 | The RealReal",
        "product_confidence": "8",
        "crawled_time": "2022-04-13 07:26:54",
        "created_time": "2022-04-13 07:21:48",
        "width": null,
        "height": null,
        "issue": "HTTP Error 403: Forbidden",
        "description": "<ul><li>Saint Laurent Leather Ankle Moto Boots</li><li>Black</li><li>Semi-Pointed Toes</li><li>Wrap-Around Straps & Buckle Closure at Sides</li><li>Includes Box & Dust Bag</li></ul><p><strong>Fit:</strong> This style typically runs a half size small.</p>",
        "domain": "therealreal.com",
        "source": "PARENT_URL",
        "brand": null,
        "slug": "saint-laurent-leather-moto-boots-black-boots-shoes-snt175465-the-realreal-19625445805",
        "tags": "alberto fasciani,ankle,ankle boots,black,boot,boots,chelsea,farfetch,lace,leather,officine creative,officine creative ga,revolve,up,up ankle,up ankle boots,up boots,up leather boots",
        "price_updated": null,
        "last_update": "2022-04-13 08:28:14",
        "currency": null,
        "price_old": null,
        "discount": null,
        "s3_url": null
    },
    {
        "page_id": "19625445791",
        "url": "http://therealreal.com/products/women/shoes/boots/alexander-mcqueen-skull-leather-moto-boots-d5vdc",
        "canonical_url": "https://www.therealreal.com/products/women/shoes/boots/alexander-mcqueen-skull-leather-moto-boots-d5vdc",
        "parent_url": "http://www.therealreal.com/shop/women/shoes/boots",
        "image_url": "https://product-images.therealreal.com/ALE123521_1_enlarged.jpg",
        "price": "$325.00",
        "name": "Alexander McQueen Skull Leather Moto Boots - Black Boots, Shoes - ALE123521 | The RealReal",
        "product_confidence": "8",
        "crawled_time": "2022-04-13 07:27:05",
        "created_time": "2022-04-13 07:21:48",
        "width": null,
        "height": null,
        "issue": "HTTP Error 403: Forbidden",
        "description": "<ul><li>Alexander McQueen Leather Ankle Moto Boots</li><li>Black</li><li>Skull</li><li>Round-Toes</li><li>Wedge Heels</li><li>Wrap-Around Straps</li><li>Includes Dust Bag</li></ul>",
        "domain": "therealreal.com",
        "source": "PARENT_URL",
        "brand": null,
        "slug": "alexander-mcqueen-skull-leather-moto-boots-black-boots-shoes-ale123521-the-realreal-19625445791",
        "tags": "ankle,ankle boots,black,boot,boots,chelsea,chelsea boots,farfetch,fwrd,leather,leather ankle,logo,officine creative,plaque ankle boots,salvatore ferragamo ,sergio rossi,via roma 15,zip",
        "price_updated": null,
        "last_update": "2022-04-13 08:28:54",
        "currency": null,
        "price_old": null,
        "discount": null,
        "s3_url": null
    },
    {
        "page_id": "19625445776",
        "url": "http://therealreal.com/products/women/shoes/boots/prada-nylon-combat-boots-d57o9",
        "canonical_url": "https://www.therealreal.com/products/women/shoes/boots/prada-nylon-combat-boots-d57o9",
        "parent_url": "http://www.therealreal.com/shop/women/shoes/boots",
        "image_url": "https://product-images.therealreal.com/PRA642487_1_enlarged.jpg",
        "price": "$645.00",
        "name": "Prada Nylon Combat Boots - Black Boots, Shoes - PRA642487 | The RealReal",
        "product_confidence": "8",
        "crawled_time": "2022-04-13 07:27:10",
        "created_time": "2022-04-13 07:21:48",
        "width": null,
        "height": null,
        "issue": "HTTP Error 403: Forbidden",
        "description": "<ul><li>Prada Nylon Ankle Combat Boots</li><li>Black</li><li>Leather Trim</li><li>Round-Toes</li><li>Platform</li><li>Lace-Up Closure at Uppers</li><li>Includes Dust Bag</li></ul><p><strong>Fit:</strong> This style typically runs a half size small.</p>",
        "domain": "therealreal.com",
        "source": "PARENT_URL",
        "brand": null,
        "slug": "prada-nylon-combat-boots-black-boots-shoes-pra642487-the-realreal-19625445776",
        "tags": "ankle,ankle boots,black,boot,boots,chunky,combat,farfetch,lace,leather,stuart weitzman,up,up ankle,up ankle boots,up boots,up combat boots,up leather,up leather boots",
        "price_updated": null,
        "last_update": "2022-04-13 08:29:15",
        "currency": null,
        "price_old": null,
        "discount": null,
        "s3_url": null
    },
    {
        "page_id": "19625445768",
        "url": "http://therealreal.com/products/women/shoes/boots/chanel-2016-interlocking-cc-logo-combat-boots-d09rh",
        "canonical_url": "https://www.therealreal.com/products/women/shoes/boots/chanel-2016-interlocking-cc-logo-combat-boots-d09rh",
        "parent_url": "http://www.therealreal.com/shop/women/shoes/boots",
        "image_url": "https://product-images.therealreal.com/CHA690879_1_enlarged.jpg",
        "price": "$695.00",
        "name": "Chanel 2016 Interlocking CC Logo Combat Boots - Black Boots, Shoes - CHA690879 | The RealReal",
        "product_confidence": "8",
        "crawled_time": "2022-04-13 07:27:17",
        "created_time": "2022-04-13 07:21:48",
        "width": null,
        "height": null,
        "issue": "HTTP Error 403: Forbidden",
        "description": "<ul><li>Chanel Leather Mid-Calf Combat Boots</li><li>From the Fall 2016 Collection by Karl Lagerfeld</li><li>Black</li><li>Interlocking CC Logo</li><li>Patent Leather Trim</li><li>Round-Toes</li><li>Block Heels</li><li>Exposed Zip Closure at Sides</li><li>Includes Box & Dust Bag</li></ul><p><strong>Fit:</strong> This style typically runs a full size small.</p>",
        "domain": "therealreal.com",
        "source": "PARENT_URL",
        "brand": null,
        "slug": "chanel-2016-interlocking-cc-logo-combat-boots-black-boots-shoes-cha690879-the-realreal-19625445768",
        "tags": "ankle,ankle boots,black,black boots shoes,boots,bottega veneta,calf,calf boots,cowboy,farfetch,knee,leather,leather boots,length,mid,via roma,via roma 15,zip ankle boots",
        "price_updated": null,
        "last_update": "2022-04-13 08:29:27",
        "currency": null,
        "price_old": null,
        "discount": null,
        "s3_url": null
    },
    {
        "page_id": "19625445727",
        "url": "http://therealreal.com/products/women/shoes/boots/chloe-leather-lace-up-boots-d7meo",
        "canonical_url": "https://www.therealreal.com/products/women/shoes/boots/chloe-leather-lace-up-boots-d7meo",
        "parent_url": "http://www.therealreal.com/shop/women/shoes/boots",
        "image_url": "https://product-images.therealreal.com/CHL203564_1_enlarged.jpg",
        "price": "$275.00",
        "name": "Chlo\u00e9 Leather Lace-Up Boots - Brown Boots, Shoes - CHL203564 | The RealReal",
        "product_confidence": "8",
        "crawled_time": "2022-04-13 07:27:55",
        "created_time": "2022-04-13 07:21:48",
        "width": null,
        "height": null,
        "issue": "HTTP Error 403: Forbidden",
        "description": "<ul><li>Chlo\u00e9 Leather Ankle Lace-Up Boots</li><li>Brown</li><li>Rubber Trim</li><li>Round-Toes</li><li>Block Heels</li><li>Lace-Up Closure at Uppers</li><li>Includes Dust Bag</li></ul><p><strong>Fit:</strong> This style typically runs a half size small.</p>",
        "domain": "therealreal.com",
        "source": "PARENT_URL",
        "brand": null,
        "slug": "chloe-leather-laceup-boots-brown-boots-shoes-chl203564-the-realreal-19625445727",
        "tags": "ankle,ankle boots,black,boot,boots,farfetch,giuseppe zanotti,giuseppe zanotti lac,lace,leather,revolve,up,up ankle,up ankle boots,up boots,valentino garavani,valentino garavani l,zanotti",
        "price_updated": null,
        "last_update": "2022-04-13 08:30:55",
        "currency": null,
        "price_old": null,
        "discount": null,
        "s3_url": null
    },
    {
        "page_id": "19625445560",
        "url": "http://therealreal.com/products/women/shoes/boots/saint-laurent-satin-crystal-embellishments-boots-d6oaq",
        "canonical_url": "https://www.therealreal.com/products/women/shoes/boots/saint-laurent-satin-crystal-embellishments-boots-d6oaq",
        "parent_url": "http://www.therealreal.com/shop/women/shoes/boots",
        "image_url": "https://product-images.therealreal.com/SNT175020_1_enlarged.jpg",
        "price": "$475.00",
        "name": "Saint Laurent Satin Crystal Embellishments Boots - Black Boots, Shoes - SNT175020 | The RealReal",
        "product_confidence": "8",
        "crawled_time": "2022-04-13 07:28:49",
        "created_time": "2022-04-13 07:21:48",
        "width": null,
        "height": null,
        "issue": "HTTP Error 403: Forbidden",
        "description": "<ul><li>Saint Laurent Satin Ankle Boots</li><li>Black</li><li>Semi-Pointed Toes with Crystal Embellishments</li><li>Block Heels</li><li>Lace-Up Closure at Uppers</li><li>Includes Box & Dust Bag</li></ul><p><strong>Fit:</strong> This style typically runs a half size small.</p>",
        "domain": "therealreal.com",
        "source": "PARENT_URL",
        "brand": null,
        "slug": "saint-laurent-satin-crystal-embellishments-boots-black-boots-shoes-snt175020-the-realreal-19625445560",
        "tags": "ankle,ankle boots,black,black boots,black boots shoes,bootie,boots,farfetch,gianvito rossi,heel,heel ankle boots,heel boots,leather,revolve,rossi,saint laurent,suede,toe ankle boots",
        "price_updated": null,
        "last_update": "2022-04-13 08:32:59",
        "currency": null,
        "price_old": null,
        "discount": null,
        "s3_url": null
    },
    {
        "page_id": "19625445512",
        "url": "http://therealreal.com/products/women/shoes/boots/valentino-rockstud-accents-leather-moto-boots-d7hw3",
        "canonical_url": "https://www.therealreal.com/products/women/shoes/boots/valentino-rockstud-accents-leather-moto-boots-d7hw3",
        "parent_url": "http://www.therealreal.com/shop/women/shoes/boots",
        "image_url": "https://product-images.therealreal.com/VAL265851_1_enlarged.jpg",
        "price": "$545.00",
        "name": "Valentino Rockstud Accents Leather Moto Boots - Black Boots, Shoes - VAL265851 | The RealReal",
        "product_confidence": "8",
        "crawled_time": "2022-04-13 07:29:01",
        "created_time": "2022-04-13 07:21:48",
        "width": null,
        "height": null,
        "issue": "HTTP Error 403: Forbidden",
        "description": "<ul><li>Valentino Leather Ankle Moto Boots</li><li>Black</li><li>Rockstud Accents</li><li>Round-Toes</li><li>Block Heels</li><li>Buckle Closures at Uppers & Sides</li><li>Wrap-Around Straps</li><li>Includes Box & Dust Bag</li></ul><p><strong>Fit:</strong> This style typically runs a half size to a full size small.</p>",
        "domain": "therealreal.com",
        "source": "PARENT_URL",
        "brand": null,
        "slug": "valentino-rockstud-accents-leather-moto-boots-black-boots-shoes-val265851-the-realreal-19625445512",
        "tags": "ankle,ankle boots,black,black boots shoes,bootie,boots,farfetch,giuseppe zanotti,heel,heel boots,lace,leather,leather boots,revolve,up,up ankle boots,valentino garavani,valentino garavani r",
        "price_updated": null,
        "last_update": "2022-04-13 08:33:39",
        "currency": null,
        "price_old": null,
        "discount": null,
        "s3_url": null
    },
    {
        "page_id": "19625445509",
        "url": "http://therealreal.com/products/women/shoes/boots/gucci-dionysus-accent-leather-boots-d7i00",
        "canonical_url": "https://www.therealreal.com/products/women/shoes/boots/gucci-dionysus-accent-leather-boots-d7i00",
        "parent_url": "http://www.therealreal.com/shop/women/shoes/boots",
        "image_url": "https://product-images.therealreal.com/GUC915509_1_enlarged.jpg",
        "price": "$645.00",
        "name": "Gucci Dionysus Accent Leather Boots - Gold Boots, Shoes - GUC915509 | The RealReal",
        "product_confidence": "8",
        "crawled_time": "2022-04-13 07:29:08",
        "created_time": "2022-04-13 07:21:48",
        "width": null,
        "height": null,
        "issue": "HTTP Error 403: Forbidden",
        "description": "<ul><li>Gucci Leather Mid-Calf Boots</li><li>By Alessandro Michele</li><li>Gold & Metallic</li><li>Animal Print</li><li>Dionysus Accent</li><li>Square-Toes</li><li>Block Heels</li><li>Buckle Closure At Uppers & Concealed Zip Closure at Ankles</li><li>Includes Dust Bag</li></ul><p><strong>Fit:</strong> This style typically runs a half size small.</p>",
        "domain": "therealreal.com",
        "source": "PARENT_URL",
        "brand": null,
        "slug": "gucci-dionysus-accent-leather-boots-gold-boots-shoes-guc915509-the-realreal-19625445509",
        "tags": "black,boot,boot black,boot dark brown,boots,farfetch,high,high boots,high leather,high leather boots,knee,leather,length,length boots,stuart,stuart weitzman,stuart weitzman 5050,weitzman",
        "price_updated": null,
        "last_update": "2022-04-13 08:33:52",
        "currency": null,
        "price_old": null,
        "discount": null,
        "s3_url": null
    },
    {
        "page_id": "19625445501",
        "url": "http://therealreal.com/products/women/shoes/boots/hermes-virginia-leather-boots-d7rbh",
        "canonical_url": "https://www.therealreal.com/products/women/shoes/boots/hermes-virginia-leather-boots-d7rbh",
        "parent_url": "http://www.therealreal.com/shop/women/shoes/boots",
        "image_url": "https://product-images.therealreal.com/HER405093_1_enlarged.jpg",
        "price": "$845.00",
        "name": "Herm\u00e8s Virginia Leather Boots - Black Boots, Shoes - HER405093 | The RealReal",
        "product_confidence": "8",
        "crawled_time": "2022-04-13 07:29:22",
        "created_time": "2022-04-13 07:21:48",
        "width": null,
        "height": null,
        "issue": "HTTP Error 403: Forbidden",
        "description": "<ul><li>Herm\u00e8s Virginia Ankle Boots</li><li>Black Leather</li><li>Pointed-Toes</li><li>Stiletto Heels</li><li>Concealed Zip Closure at Uppers</li><li>Includes Dust Bag</li></ul><p><strong>Designer Fit:</strong> Boots by Herm\u00e8s typically run a half size small.</p>",
        "domain": "therealreal.com",
        "source": "PARENT_URL",
        "brand": null,
        "slug": "hermes-virginia-leather-boots-black-boots-shoes-her405093-the-realreal-19625445501",
        "tags": "ankle,ankle boots,black,boots,farfetch,gianvito rossi,heel,heel ankle boots,jimmy choo,leather,maison margiela tabi,manolo blahnik,manolo blahnik hangi,pointed,pumps,rossi,toe,toe pumps",
        "price_updated": null,
        "last_update": "2022-04-13 08:34:25",
        "currency": null,
        "price_old": null,
        "discount": null,
        "s3_url": null
    },
    {
        "page_id": "19625445384",
        "url": "http://therealreal.com/products/women/shoes/boots/stuart-weitzman-alligator-printed-chelsea-boots-d83a9",
        "canonical_url": "https://www.therealreal.com/products/women/shoes/boots/stuart-weitzman-alligator-printed-chelsea-boots-d83a9",
        "parent_url": "http://www.therealreal.com/shop/women/shoes/boots",
        "image_url": "https://product-images.therealreal.com/WSU198715_1_enlarged.jpg",
        "price": "$245.00",
        "name": "Stuart Weitzman Alligator Printed Chelsea Boots - Pink Boots, Shoes - WSU198715 | The RealReal",
        "product_confidence": "8",
        "crawled_time": "2022-04-13 07:29:59",
        "created_time": "2022-04-13 07:21:48",
        "width": null,
        "height": null,
        "issue": "HTTP Error 403: Forbidden",
        "description": "<ul><li>Stuart Weitzman Alligator Ankle Chelsea Boots</li><li>Pink</li><li>Printed</li><li>Round-Toes</li><li>Block Heels with Platform</li><li>Includes Dust Bag</li></ul><p><strong>Designer Fit:</strong> This designer typically runs true to size.</p><p>Unfortunately, due to restrictions, this item may not be eligible for shipping in all areas.</p>",
        "domain": "therealreal.com",
        "source": "PARENT_URL",
        "brand": null,
        "slug": "stuart-weitzman-alligator-printed-chelsea-boots-pink-boots-shoes-wsu198715-the-realreal-19625445384",
        "tags": "ankle,ankle boots,black,boot,boots,chelsea,farfetch,fwrd,heel ankle boots,leather,leather ankle,leather boots,stuart,stuart weitzman,stuart weitzman nora,toe ankle boots,up boots,weitzman",
        "price_updated": null,
        "last_update": "2022-04-13 08:35:46",
        "currency": null,
        "price_old": null,
        "discount": null,
        "s3_url": null
    },
    {
        "page_id": "19625445379",
        "url": "http://therealreal.com/products/women/shoes/boots/paris-texas-leather-ruffle-embellishment-slouch-boots-d5kww",
        "canonical_url": "https://www.therealreal.com/products/women/shoes/boots/paris-texas-leather-ruffle-embellishment-slouch-boots-d5kww",
        "parent_url": "http://www.therealreal.com/shop/women/shoes/boots",
        "image_url": "https://product-images.therealreal.com/WPART21801_1_enlarged.jpg",
        "price": "$395.00",
        "name": "Paris Texas Leather Ruffle Embellishment Slouch Boots - Black Boots, Shoes - WPART21801 | The RealR",
        "product_confidence": "8",
        "crawled_time": "2022-04-13 07:30:04",
        "created_time": "2022-04-13 07:21:48",
        "width": null,
        "height": null,
        "issue": "HTTP Error 403: Forbidden",
        "description": "<ul><li>Paris Texas Leather Mid-Calf Slouch Boots</li><li>Black</li><li>Pointed-Toes with Ruffle Embellishment</li><li>Stiletto Heels</li><li>Includes Box & Dust Bag</li></ul><p><strong>Designer Fit:</strong> Boots by Paris Texas typically run true to size.</p>",
        "domain": "therealreal.com",
        "source": "PARENT_URL",
        "brand": null,
        "slug": "paris-texas-leather-ruffle-embellishment-slouch-boots-black-boots-shoes-wpart21801-the-realr-19625445379",
        "tags": "ankle,ankle boots,black,black boots,black boots shoes,boot,boots,farfetch,leather,paris,paris texas,pointed,stuart weitzman,stuart weitzman poin,texas,toe,toe ankle,toe ankle boots",
        "price_updated": null,
        "last_update": "2022-04-13 08:36:06",
        "currency": null,
        "price_old": null,
        "discount": null,
        "s3_url": null
    },
    {
        "page_id": "19625445339",
        "url": "http://therealreal.com/products/women/shoes/boots/saint-laurent-leather-boots-d72rt",
        "canonical_url": "https://www.therealreal.com/products/women/shoes/boots/saint-laurent-leather-boots-d72rt",
        "parent_url": "http://www.therealreal.com/shop/women/shoes/boots",
        "image_url": "https://product-images.therealreal.com/SNT175162_1_enlarged.jpg",
        "price": "$1125.00",
        "name": "Saint Laurent Leather Boots - Black Boots, Shoes - SNT175162 | The RealReal",
        "product_confidence": "8",
        "crawled_time": "2022-04-13 07:30:18",
        "created_time": "2022-04-13 07:21:48",
        "width": null,
        "height": null,
        "issue": "HTTP Error 403: Forbidden",
        "description": "<ul><li>Saint Laurent Leather Over-The-Knee Boots</li><li>Black</li><li>Pointed-Toes</li><li>Cone Heels</li><li>Includes Dust Bag</li></ul><p><strong>Fit:</strong> This style typically runs a half size small.</p>",
        "domain": "therealreal.com",
        "source": "PARENT_URL",
        "brand": null,
        "slug": "saint-laurent-leather-boots-black-boots-shoes-snt175162-the-realreal-19625445339",
        "tags": "black,black boots shoes,boots,farfetch,high,high boots,high leather boots,knee,knee boots,leather,length,length boots,paul warmer knee,saint laurent,stuart,stuart weitzman,thigh,weitzman",
        "price_updated": null,
        "last_update": "2022-04-13 08:36:27",
        "currency": null,
        "price_old": null,
        "discount": null,
        "s3_url": null
    },
    {
        "page_id": "19625445228",
        "url": "http://therealreal.com/products/women/shoes/boots/chanel-2018-interlocking-cc-logo-combat-boots-d5b8j",
        "canonical_url": "https://www.therealreal.com/products/women/shoes/boots/chanel-2018-interlocking-cc-logo-combat-boots-d5b8j",
        "parent_url": "http://www.therealreal.com/shop/women/shoes/boots",
        "image_url": "https://product-images.therealreal.com/CHA697052_1_enlarged.jpg",
        "price": "$2000.00",
        "name": "Chanel 2018 Interlocking CC Logo Combat Boots - Black Boots, Shoes - CHA697052 | The RealReal",
        "product_confidence": "8",
        "crawled_time": "2022-04-13 07:30:31",
        "created_time": "2022-04-13 07:21:47",
        "width": null,
        "height": null,
        "issue": "HTTP Error 403: Forbidden",
        "description": "<ul><li>Chanel Leather Ankle Combat Boots</li><li>From the 2018 Collection</li><li>Black</li><li>Interlocking CC Logo, Faux Pearl Accents & Chain-Link Accent</li><li>Rubber Trim</li><li>Round-Toes</li><li>Block Heels with Platform</li><li>Lace-Up & Snap Closures at Uppers</li><li>Includes Box & Dust Bag</li></ul><p><strong>Fit:</strong> This style typically runs a full size small.</p>",
        "domain": "therealreal.com",
        "source": "PARENT_URL",
        "brand": null,
        "slug": "chanel-2018-interlocking-cc-logo-combat-boots-black-boots-shoes-cha697052-the-realreal-19625445228",
        "tags": "ankle,ankle boots,black,boots,combat,creative,farfetch,lace,leather,officine,officine creative,officine creative la,up,up ankle,up ankle boots,up boots,up leather,up leather boots",
        "price_updated": null,
        "last_update": "2022-04-13 08:36:57",
        "currency": null,
        "price_old": null,
        "discount": null,
        "s3_url": null
    },
    {
        "page_id": "19625445049",
        "url": "http://therealreal.com/products/women/shoes/boots/fendi-sock-boots-d5y5k",
        "canonical_url": "https://www.therealreal.com/products/women/shoes/boots/fendi-sock-boots-d5y5k",
        "parent_url": "http://www.therealreal.com/shop/women/shoes/boots",
        "image_url": "https://product-images.therealreal.com/FEN208499_1_enlarged.jpg",
        "price": "$745.00",
        "name": "Fendi Sock Boots - Black Boots, Shoes - FEN208499 | The RealReal",
        "product_confidence": "8",
        "crawled_time": "2022-04-13 07:31:31",
        "created_time": "2022-04-13 07:21:47",
        "width": null,
        "height": null,
        "issue": "HTTP Error 403: Forbidden",
        "description": "<ul><li>Fendi Over-The-Knee Sock Boots</li><li>Black</li><li>Leather Trim</li><li>Semi-Pointed Toes</li><li>Block Heels</li><li>Includes Dust Bag</li></ul><p><strong>Designer Fit:</strong> Boots by Fendi typically run a half size small.</p>",
        "domain": "therealreal.com",
        "source": "PARENT_URL",
        "brand": null,
        "slug": "fendi-sock-boots-black-boots-shoes-fen208499-the-realreal-19625445049",
        "tags": "black,boots,farfetch,high,high boots,high leather,high leather boots,knee,knee boots,leather,length boots,stuart,stuart weitzman,stuart weitzman 5050,stuart weitzman knee,the,thigh,weitzman",
        "price_updated": null,
        "last_update": "2022-04-13 08:39:01",
        "currency": null,
        "price_old": null,
        "discount": null,
        "s3_url": null
    },
    {
        "page_id": "19625444937",
        "url": "http://therealreal.com/products/women/shoes/boots/valentino-suede-boots-d5ivx",
        "canonical_url": "https://www.therealreal.com/products/women/shoes/boots/valentino-suede-boots-d5ivx",
        "parent_url": "http://www.therealreal.com/shop/women/shoes/boots",
        "image_url": "https://product-images.therealreal.com/VAL264960_1_enlarged.jpg",
        "price": "$305.00",
        "name": "Valentino Suede Boots - Black Boots, Shoes - VAL264960 | The RealReal",
        "product_confidence": "8",
        "crawled_time": "2022-04-13 07:32:03",
        "created_time": "2022-04-13 07:21:47",
        "width": null,
        "height": null,
        "issue": "HTTP Error 403: Forbidden",
        "description": "<ul><li>Valentino Suede Mid-Calf Boots</li><li>Black</li><li>Pointed-Toes</li><li>Cone Heels</li><li>Includes Box & Dust Bag</li></ul><p><strong>Fit:</strong> This style typically runs a half size to a full size small.</p>",
        "domain": "therealreal.com",
        "source": "PARENT_URL",
        "brand": null,
        "slug": "valentino-suede-boots-black-boots-shoes-val264960-the-realreal-19625444937",
        "tags": "ankle,ankle boots,black,black boots,black boots shoes,boot,boots,farfetch,gia borghini x,knee,leather,leather boots,length boots,paris,paris texas,paris texas slouched,suede,texas",
        "price_updated": null,
        "last_update": "2022-04-13 08:39:32",
        "currency": null,
        "price_old": null,
        "discount": null,
        "s3_url": null
    },
    {
        "page_id": "19625444927",
        "url": "http://therealreal.com/products/women/shoes/boots/moncler-nylon-boots-d7m7q",
        "canonical_url": "https://www.therealreal.com/products/women/shoes/boots/moncler-nylon-boots-d7m7q",
        "parent_url": "http://www.therealreal.com/shop/women/shoes/boots",
        "image_url": "https://product-images.therealreal.com/MOC78935_1_enlarged.jpg",
        "price": "$495.00",
        "name": "Moncler Nylon Boots - Black Boots, Shoes - MOC78935 | The RealReal",
        "product_confidence": "8",
        "crawled_time": "2022-04-13 07:32:17",
        "created_time": "2022-04-13 07:21:47",
        "width": null,
        "height": null,
        "issue": "HTTP Error 403: Forbidden",
        "description": "<ul><li>Moncler Nylon Knee-High Boots</li><li>Black</li><li>Round-Toes</li><li>Wedge Heels with Platform</li><li>Includes Box & Dust Bag</li></ul><p><strong>Designer Fit:</strong> Boots by Moncler typically run a half size small.</p>",
        "domain": "therealreal.com",
        "source": "PARENT_URL",
        "brand": null,
        "slug": "moncler-nylon-boots-black-boots-shoes-moc78935-the-realreal-19625444927",
        "tags": "black,boots,farfetch,high,high boots,high leather,high leather boots,knee,lace,leather,leather boots,length,length boots,stuart,stuart weitzman,stuart weitzman 5050,via roma 15,weitzman",
        "price_updated": null,
        "last_update": "2022-04-13 08:40:03",
        "currency": null,
        "price_old": null,
        "discount": null,
        "s3_url": null
    },
    {
        "page_id": "19625444906",
        "url": "http://therealreal.com/products/women/shoes/boots/prada-leather-boots-d88iv",
        "canonical_url": "https://www.therealreal.com/products/women/shoes/boots/prada-leather-boots-d88iv",
        "parent_url": "http://www.therealreal.com/shop/women/shoes/boots",
        "image_url": "https://product-images.therealreal.com/PRA646483_1_enlarged.jpg",
        "price": "$375.00",
        "name": "Prada Leather Boots - Black Boots, Shoes - PRA646483 | The RealReal",
        "product_confidence": "8",
        "crawled_time": "2022-04-13 07:32:24",
        "created_time": "2022-04-13 07:21:47",
        "width": null,
        "height": null,
        "issue": "HTTP Error 403: Forbidden",
        "description": "<ul><li>Prada Leather Over-The-Knee Boots</li><li>Black</li><li>Semi-Pointed Toes</li><li>Block Heels</li><li>Includes Dust Bag</li></ul><p><strong>Fit:</strong> This style typically runs a half size small.</p>",
        "domain": "therealreal.com",
        "source": "PARENT_URL",
        "brand": null,
        "slug": "prada-leather-boots-black-boots-shoes-pra646483-the-realreal-19625444906",
        "tags": "black,black boots shoes,boot,boots,farfetch,heel boots,high,high boots,knee,leather,length,length boots,stuart,stuart weitzman,stuart weitzman knee,via roma,via roma 15,weitzman",
        "price_updated": null,
        "last_update": "2022-04-13 08:40:12",
        "currency": null,
        "price_old": null,
        "discount": null,
        "s3_url": null
    },
    {
        "page_id": "19625441447",
        "url": "http://therealreal.com/products/women/shoes/sandals/gucci-rubber-striped-slides-w-tags-d5yzv",
        "canonical_url": "https://www.therealreal.com/products/women/shoes/sandals/gucci-rubber-striped-slides-w-tags-d5yzv",
        "parent_url": "http://www.therealreal.com/shop/women/shoes",
        "image_url": "https://product-images.therealreal.com/GUC911202_1_enlarged.jpg",
        "price": "$395.00",
        "name": "Gucci Rubber Striped Slides w/ Tags - Black Sandals, Shoes - GUC911202 | The RealReal",
        "product_confidence": "8",
        "crawled_time": "2022-04-13 07:21:24",
        "created_time": "2022-04-13 07:20:57",
        "width": null,
        "height": null,
        "issue": "HTTP Error 403: Forbidden",
        "description": "<ul><li>Gucci Rubber Slides</li><li>Black, Green & Red</li><li>Striped</li><li>Bow Accents</li><li>Includes Box & Dust Bag</li></ul>",
        "domain": "therealreal.com",
        "source": "PARENT_URL",
        "brand": null,
        "slug": "gucci-rubber-striped-slides-w-tags-black-sandals-shoes-guc911202-the-realreal-19625441447",
        "tags": "alexander mcqueen,alexander mcqueen lo,balenciaga raised lo,black,embossed slides,farfetch,fwrd,logo,moschino,moschino logo,moschino logo plaque,plaque slides,pool,print,print slides,revolve,sandals,slides",
        "price_updated": null,
        "last_update": "2022-04-13 08:15:33",
        "currency": null,
        "price_old": null,
        "discount": null,
        "s3_url": null
    },
    {
        "page_id": "19625441236",
        "url": "http://therealreal.com/products/women/shoes/sandals/gucci-leather-floral-print-sandals-d8sf5",
        "canonical_url": "https://www.therealreal.com/products/women/shoes/sandals/gucci-leather-floral-print-sandals-d8sf5",
        "parent_url": "http://www.therealreal.com/shop/women/shoes",
        "image_url": "https://product-images.therealreal.com/GUC916789_1_enlarged.jpg",
        "price": "$750.00",
        "name": "Gucci Leather Floral Print Sandals - Neutrals Sandals, Shoes - GUC916789 | The RealReal",
        "product_confidence": "8",
        "crawled_time": "2022-04-13 07:45:39",
        "created_time": "2022-04-13 07:20:55",
        "width": null,
        "height": null,
        "issue": "HTTP Error 403: Forbidden",
        "description": "<ul><li>Gucci Leather Sandals</li><li>Neutrals</li><li>Floral Print</li><li>Stiletto Heels</li><li>Multistrap & Buckle Closure at Ankles</li><li>Includes Box & Dust Bag</li></ul>",
        "domain": "therealreal.com",
        "source": "PARENT_URL",
        "brand": null,
        "slug": "gucci-leather-floral-print-sandals-neutrals-sandals-shoes-guc916789-the-realreal-19625441236",
        "tags": "100mm,bottega veneta stret,embellished,farfetch,francesco russo,francesco russo cut,garavani,gianvito rossi,pumps,ren\u00e9 caovilla,revolve,rockstud,sandals,strappy,stuart weitzman,valentino,valentino garavani,valentino garavani r",
        "price_updated": null,
        "last_update": "2022-04-13 08:56:16",
        "currency": null,
        "price_old": null,
        "discount": null,
        "s3_url": null
    },
    {
        "page_id": "19625441222",
        "url": "http://therealreal.com/products/women/shoes/boots/salvatore-ferragamo-suede-faux-fur-trim-riding-boots-d0xac",
        "canonical_url": "https://www.therealreal.com/products/women/shoes/boots/salvatore-ferragamo-suede-faux-fur-trim-riding-boots-d0xac",
        "parent_url": "http://www.therealreal.com/shop/women/shoes",
        "image_url": "https://product-images.therealreal.com/SAL225941_1_enlarged.jpg",
        "price": "$130.00",
        "name": "Salvatore Ferragamo Suede Faux Fur Trim Riding Boots - Brown Boots, Shoes - SAL225941 | The RealRea",
        "product_confidence": "8",
        "crawled_time": "2022-04-13 07:45:50",
        "created_time": "2022-04-13 07:20:55",
        "width": null,
        "height": null,
        "issue": "HTTP Error 403: Forbidden",
        "description": "<ul><li>Salvatore Ferragamo Suede Knee-High Riding Boots</li><li>Brown</li><li>Round-Toes with Faux Fur Trim</li><li>Block Heels</li><li>Includes Dust Bag</li></ul><p><strong>Designer Fit:</strong> Boots by Salvatore Ferragamo typically run a half size small.</p>",
        "domain": "therealreal.com",
        "source": "PARENT_URL",
        "brand": null,
        "slug": "salvatore-ferragamo-suede-faux-fur-trim-riding-boots-brown-boots-shoes-sal225941-the-realrea-19625441222",
        "tags": "ankle,black,black boots shoes,boots,farfetch,gia borghini,high,high boots,knee,lace,leather,leather boots,length,length boots,noelle camel chunky,sole lace detail,stuart weitzman,up",
        "price_updated": null,
        "last_update": "2022-04-13 08:56:29",
        "currency": null,
        "price_old": null,
        "discount": null,
        "s3_url": null
    },
    {
        "page_id": "19625416073",
        "url": "http://therealreal.com/products/women/handbags/handle-bags/cult-gaia-acrylic-cutout-handle-bag-d6znr",
        "canonical_url": "https://www.therealreal.com/products/women/handbags/handle-bags/cult-gaia-acrylic-cutout-handle-bag-d6znr",
        "parent_url": "http://www.therealreal.com/shop/women/handbags/handle-bags",
        "image_url": "https://product-images.therealreal.com/WGAIA27685_1_enlarged.jpg",
        "price": "$105.00",
        "name": "Cult Gaia Acrylic Cutout Handle Bag - Brown Handle Bags, Handbags - WGAIA27685 | The RealReal",
        "product_confidence": "6",
        "crawled_time": "2022-04-13 07:17:08",
        "created_time": "2022-04-13 07:16:59",
        "width": null,
        "height": null,
        "issue": "HTTP Error 403: Forbidden",
        "description": "<ul><li>Cult Gaia Top Handle Bag</li><li>Brown</li><li>Printed</li><li>Unlined</li><li>Open Top</li><li>Includes Dust Bag</li></ul>",
        "domain": "therealreal.com",
        "source": "PARENT_URL",
        "brand": null,
        "slug": "cult-gaia-acrylic-cutout-handle-bag-brown-handle-bags-handbags-wgaia27685-the-realreal-19625416073",
        "tags": "bag,boutique,clutch,clutch bag,etro paisley,farfetch,free people,jimmy choo,jimmy choo emmie,kurt geiger london,lego jurassic world,prettylittlething,print,print scarf,scarf,set,shoptiques,wallet",
        "price_updated": null,
        "last_update": "2022-04-13 08:07:16",
        "currency": null,
        "price_old": null,
        "discount": null,
        "s3_url": null
    },
    {
        "page_id": "19625416063",
        "url": "http://therealreal.com/products/women/handbags/handle-bags/carolina-santo-domingo-canvas-handle-bag-d6wzk",
        "canonical_url": "https://www.therealreal.com/products/women/handbags/handle-bags/carolina-santo-domingo-canvas-handle-bag-d6wzk",
        "parent_url": "http://www.therealreal.com/shop/women/handbags/handle-bags",
        "image_url": "https://product-images.therealreal.com/WCSAD20379_1_enlarged.jpg",
        "price": "$375.00",
        "name": "Carolina Santo Domingo  Canvas Handle Bag - White Handle Bags, Handbags - WCSAD20379 | The RealReal",
        "product_confidence": "6",
        "crawled_time": "2022-04-13 07:17:17",
        "created_time": "2022-04-13 07:16:59",
        "width": null,
        "height": null,
        "issue": "HTTP Error 403: Forbidden",
        "description": "<ul><li>Carolina Santo Domingo Top Handle Bag</li><li>White Canvas</li><li>Gold-Tone Hardware</li><li>Leather Trim</li><li>Flat Handles & Single Adjustable Shoulder Strap</li><li>Suede Lining & Single Interior Pocket</li><li>Snap Closure at Top</li><li>Protective Feet at Base</li><li>Includes Dust Bag & Interior Zip Pouch</li></ul>",
        "domain": "therealreal.com",
        "source": "PARENT_URL",
        "brand": null,
        "slug": "carolina-santo-domingo-canvas-handle-bag-white-handle-bags-handbags-wcsad20379-the-realreal-19625416063",
        "tags": "bag,black,farfetch,isabel marant,large,logo,longchamp le pliage,louis vuitton,owned,owned garden,owned garden party,pm tote bag,pre,shoulder,shoulder bag,small,tote,tote bag",
        "price_updated": null,
        "last_update": "2022-04-13 08:07:27",
        "currency": null,
        "price_old": null,
        "discount": null,
        "s3_url": null
    },
    {
        "page_id": "19625414233",
        "url": "http://therealreal.com/products/women/handbags/crossbody-bags/mansur-gavriel-leather-crossbody-bag-d6k1r",
        "canonical_url": "https://www.therealreal.com/products/women/handbags/crossbody-bags/mansur-gavriel-leather-crossbody-bag-d6k1r",
        "parent_url": "http://www.therealreal.com/shop/women/handbags/crossbody-bags",
        "image_url": "https://product-images.therealreal.com/WGY36522_1_enlarged.jpg",
        "price": "$195.00",
        "name": "Mansur Gavriel Leather Crossbody Bag - Black Crossbody Bags, Handbags - WGY36522 | The RealReal",
        "product_confidence": "6",
        "crawled_time": "2022-04-13 07:16:47",
        "created_time": "2022-04-13 07:16:37",
        "width": null,
        "height": null,
        "issue": "HTTP Error 403: Forbidden",
        "description": "<ul><li>Mansur Gavriel Crossbody Bag</li><li>Black</li><li>Gold-Tone Hardware</li><li>Single Adjustable Shoulder Strap</li><li>Leather Lining</li><li>Drawstring Closure at Front</li></ul>",
        "domain": "therealreal.com",
        "source": "PARENT_URL",
        "brand": null,
        "slug": "mansur-gavriel-leather-crossbody-bag-black-crossbody-bags-handbags-wgy36522-the-realreal-19625414233",
        "tags": "bag,bucket,chanel pre,crossbody,crossbody bag,farfetch,leather,mansur gavriel,mansur gavriel mini,mansur gavriel zip,mini,owned,pre,shoulder,tote,tote bag,valentino garavani,valentino garavani r",
        "price_updated": null,
        "last_update": "2022-04-13 08:06:25",
        "currency": null,
        "price_old": null,
        "discount": null,
        "s3_url": null
    },
    {
        "page_id": "19625413065",
        "url": "http://therealreal.com/products/women/handbags/crossbody-bags/burberry-beckley-london-check-messenger-bag-d73za",
        "canonical_url": "https://www.therealreal.com/products/women/handbags/crossbody-bags/burberry-beckley-london-check-messenger-bag-d73za",
        "parent_url": "http://www.therealreal.com/shop/women/handbags/crossbody-bags",
        "image_url": "https://product-images.therealreal.com/BUR272935_1_enlarged.jpg",
        "price": "$425.00",
        "name": "Burberry Beckley London Check Messenger Bag - Black Crossbody Bags, Handbags - BUR272935 | The Real",
        "product_confidence": "6",
        "crawled_time": "2022-04-13 07:16:40",
        "created_time": "2022-04-13 07:16:33",
        "width": null,
        "height": null,
        "issue": "HTTP Error 403: Forbidden",
        "description": "<ul><li>Burberry Messenger Bag</li><li>Black</li><li>Silver-Tone Hardware</li><li>Single Shoulder Strap</li><li>Grosgrain Lining & Dual Interior Pockets</li><li>Buckle Closure at Front</li></ul>",
        "domain": "therealreal.com",
        "source": "PARENT_URL",
        "brand": null,
        "slug": "burberry-beckley-london-check-messenger-bag-black-crossbody-bags-handbags-bur272935-the-real-19625413065",
        "tags": "bag,crossbody,crossbody bag,farfetch,karl lagerfeld,karl lagerfeld k,laurent,leather,logo,louis vuitton,louis vuitton 2010,owned,pre,saint,saint laurent,saint laurent small,shoulder,shoulder bag",
        "price_updated": null,
        "last_update": "2022-04-13 08:06:12",
        "currency": null,
        "price_old": null,
        "discount": null,
        "s3_url": null
    },
    {
        "page_id": "19625401630",
        "url": "https://www.prettylittlething.com.au/green-nylon-phone-cross-body-bag.html",
        "canonical_url": "https://www.prettylittlething.com.au/green-nylon-phone-cross-body-bag.html",
        "parent_url": "https://www.prettylittlething.com.au/bloom-multi-sequin-backpack.html",
        "image_url": "https://cdn-img.prettylittlething.com/e/d/b/8/edb81e7acd38e720a5bb35ffe149ed0fd8dfe08e_cmw8611_1.jpg",
        "price": "$38.00",
        "name": "Green Nylon Phone Cross Body Bag",
        "product_confidence": "10",
        "crawled_time": "2022-04-13 07:15:05",
        "created_time": "2022-04-13 07:14:51",
        "width": null,
        "height": null,
        "issue": "[Errno 2] No such file or directory: 'data/test2.",
        "description": "A doll needs nothing but there phone and this unreal bag has got you covered. Featuring  green ny...",
        "domain": "prettylittlething.com.au",
        "source": "PARENT_URL",
        "brand": null,
        "slug": "green-nylon-phone-cross-body-bag-19625401630",
        "tags": "black,bodycon,bodycon dress,bodysuit,crop top,cut,cut long sleeve,detail bodycon dress,dress,long,long sleeve,long sleeve bodysuit,mesh,prettylittlething au,revolve,sleeve,tie front,top",
        "price_updated": null,
        "last_update": "2022-04-13 07:17:22",
        "currency": null,
        "price_old": null,
        "discount": null,
        "s3_url": null
    },
    // {
    //     "page_id": "19625237638",
    //     "url": "http://reddressboutique.com/products/so-divine-pink-tweed-bag",
    //     "canonical_url": "https://www.reddress.com/products/so-divine-pink-tweed-bag",
    //     "parent_url": "http://reddressboutique.com/collections/new-today/products/follow-your-heart-grey-earrings",
    //     "image_url": "http://cdn.shopify.com/s/files/1/1708/7943/products/4-5-22-PartII33499_1024x1024.jpg?v=1649857884",
    //     "price": "$5.00",
    //     "name": "Classy Pink Tweed Bag - All Accessories | Red Dress",
    //     "product_confidence": "10",
    //     "crawled_time": "2022-04-13 06:57:30",
    //     "created_time": "2022-04-13 06:57:15",
    //     "width": null,
    //     "height": null,
    //     "issue": "[Errno 2] No such file or directory: 'data/test2.",
    //     "description": "This bag features a pink tweed purse, gold hardware, a pocket inside, and it comes with chain. \u2022 All Man Made Materials \u2022 Body of bag is 8\" x 6\" x 3\" \u2022 Chain is 11\"/22\" \u2022 Imported",
    //     "domain": "reddressboutique.com",
    //     "source": "PARENT_URL",
    //     "brand": null,
    //     "slug": "classy-pink-tweed-bag-all-accessories-red-dress-19625237638",
    //     "tags": "bag,christian dior,christian dior pre,falabella,farfetch,fwrd,mini,owned,pre,red dress,shoulder,shoulder bag,stella,stella mccartney,stella mccartney min,tote,tote bag,zip falabella should",
    //     "price_updated": null,
    //     "last_update": "2022-04-13 06:58:44",
    //     "currency": null,
    //     "price_old": null,
    //     "discount": null,
    //     "s3_url": null
    // },
    // {
    //     "page_id": "19625236844",
    //     "url": "http://reddressboutique.com/products/off-the-chain-beige-bag",
    //     "canonical_url": "https://www.reddress.com/products/off-the-chain-beige-bag",
    //     "parent_url": "http://reddressboutique.com/collections/new-today/products/follow-your-heart-grey-earrings",
    //     "image_url": "http://cdn.shopify.com/s/files/1/1708/7943/products/4-5-2233037_1024x1024.jpg?v=1649857890",
    //     "price": "$5.00",
    //     "name": "Flawless Beige Bag - Accessories | Red Dress",
    //     "product_confidence": "10",
    //     "crawled_time": "2022-04-13 06:58:33",
    //     "created_time": "2022-04-13 06:57:13",
    //     "width": null,
    //     "height": null,
    //     "issue": "[Errno 2] No such file or directory: 'data/test2.",
    //     "description": "This bag features quilted stitching, flap closure with snap, and a crossbody chain strap. This bag measures approximately 9\" x 7\" with a 43\" drop strap. \u2022 Imported",
    //     "domain": "reddressboutique.com",
    //     "source": "PARENT_URL",
    //     "brand": null,
    //     "slug": "flawless-beige-bag-accessories-red-dress-19625236844",
    //     "tags": "bag,chanel pre,crossbody,crossbody bag,dress,farfetch,mccartney,michael michael kors,mini,quilted,red,red dress,shoulder,shoulder bag,stella,stella mccartney,stella mccartney min,stella mccartney ste",
    //     "price_updated": null,
    //     "last_update": "2022-04-13 07:01:55",
    //     "currency": null,
    //     "price_old": null,
    //     "discount": null,
    //     "s3_url": null
    // },
    // {
    //     "page_id": "19625023720",
    //     "url": "https://www.prettylittlething.com.au/blue-plisse-slouchy-clutch-bag.html",
    //     "canonical_url": "https://www.prettylittlething.com.au/blue-plisse-slouchy-clutch-bag.html",
    //     "parent_url": "http://prettylittlething.com.au/accessories/bags/clutches.html",
    //     "image_url": "https://cdn-img.prettylittlething.com/5/1/2/1/51216a653cae2955d08147c71df7a6a106cd0163_cmw9453_1.jpg",
    //     "price": "$45.00",
    //     "name": "Blue Plisse Slouchy Clutch Bag",
    //     "product_confidence": "10",
    //     "crawled_time": "2022-04-13 06:33:50",
    //     "created_time": "2022-04-13 06:33:43",
    //     "width": null,
    //     "height": null,
    //     "issue": "[Errno 2] No such file or directory: 'data/test2.",
    //     "description": "Add a pop of blue into your accessory wardrobe with this bag doll. Featuring a blue plisse materi...",
    //     "domain": "prettylittlething.com.au",
    //     "source": "PARENT_URL",
    //     "brand": null,
    //     "slug": "blue-plisse-slouchy-clutch-bag-19625023720",
    //     "tags": "black,blue,blue tie dye,crew neck,crop,crop top,green,hem hook eye,long sleeve,prettylittlething,prettylittlething au,rib,shirt,sleeve,sleeve crop,tie,tie waist crop,top",
    //     "price_updated": null,
    //     "last_update": "2022-04-13 06:34:51",
    //     "currency": null,
    //     "price_old": null,
    //     "discount": null,
    //     "s3_url": null
    // },
    {
        "page_id": "19625023322",
        "url": "https://www.prettylittlething.com.au/hot-pink-plisse-slouchy-clutch-bag.html",
        "canonical_url": "https://www.prettylittlething.com.au/hot-pink-plisse-slouchy-clutch-bag.html",
        "parent_url": "http://prettylittlething.com.au/accessories/bags/clutches.html",
        "image_url": "https://cdn-img.prettylittlething.com/3/c/a/2/3ca2c445c0836e2e2c39a5ccc6caf8f2544ccc59_cmw9452_1.jpg",
        "price": "$45.00",
        "name": "Hot Pink Plisse Slouchy Clutch Bag",
        "product_confidence": "10",
        "crawled_time": "2022-04-13 06:33:56",
        "created_time": "2022-04-13 06:33:42",
        "width": null,
        "height": null,
        "issue": "[Errno 2] No such file or directory: 'data/test2.",
        "description": "Add a pop of pink into your accessory wardrobe with this bag doll. Featuring a hot pink plisse ma...",
        "domain": "prettylittlething.com.au",
        "source": "PARENT_URL",
        "brand": null,
        "slug": "hot-pink-plisse-slouchy-clutch-bag-19625023322",
        "tags": "bandeau,bandeau bikini top,bikini,bikini bottoms,bikini top,black,free,free people,mura boutique,pastel pink floral,people,pink,prettylittlething,prettylittlething au,print,recycled gold multi,revolve,top",
        "price_updated": null,
        "last_update": "2022-04-13 06:35:02",
        "currency": null,
        "price_old": null,
        "discount": null,
        "s3_url": null
    },
    {
        "page_id": "19623676406",
        "url": "http://fwrd.com/product-jacquemus-le-short-bagnu/JQUF-WF26/?d=Womens&itrownum=2&itcurrpage=1&itview=05",
        "canonical_url": "https://www.fwrd.com/product-jacquemus-le-short-bagnu-in-blue-stripes/JQUF-WF26/",
        "parent_url": "https://www.fwrd.com/category-shorts/9d2482/?navsrc=clothing",
        "image_url": "https://is4.fwrdassets.com/images/p/fw/p/JQUF-WF26_V1.jpg",
        "price": "$315",
        "name": "JACQUEMUS Le Short Bagnu in Blue Stripes | FWRD",
        "product_confidence": "10",
        "crawled_time": "2022-04-13 02:41:09",
        "created_time": "2022-04-13 02:40:59",
        "width": null,
        "height": null,
        "issue": "[Errno 2] No such file or directory: 'data/test2.",
        "description": "Shop for JACQUEMUS Le Short Bagnu in Blue Stripes at FWRD. Free 2 day shipping and returns.",
        "domain": "fwrd.com",
        "source": "PARENT_URL",
        "brand": null,
        "slug": "jacquemus-le-short-bagnu-in-blue-stripes-fwrd-19623676406",
        "tags": "beyond yoga spacedye,biker short,faithfull brand,fwrd,grey,high,high waisted,jacquemus le,jacquemus le short,l,le,pink,revolve,short,shorts,space daydreamin sho,white,z supply",
        "price_updated": null,
        "last_update": "2022-04-13 02:42:18",
        "currency": null,
        "price_old": null,
        "discount": null,
        "s3_url": null
    },
    {
        "page_id": "19623654081",
        "url": "http://fwrd.com/product-loewe-flamenco-clutch-bag/LOEW-WY669/?d=Womens&itrownum=3&itcurrpage=1&itview=05",
        "canonical_url": "https://www.fwrd.com/product-loewe-flamenco-clutch-bag-in-ash-grey/LOEW-WY669/",
        "parent_url": "https://www.fwrd.com/category-bags/2df9df/?navsrc=hpbig2&featuredCodes=BOTT-WY752,BOTT-WY753,ALIA-WY49,TERX-WY142,OFFF-WY107,TERX-WY143,SLAU-WY1810,MI",
        "image_url": "https://is4.fwrdassets.com/images/p/fw/p/LOEW-WY669_V1.jpg",
        "price": "$2450",
        "name": "Loewe Flamenco Clutch Bag in Ash Grey | FWRD",
        "product_confidence": "10",
        "crawled_time": "2022-04-13 02:37:45",
        "created_time": "2022-04-13 02:37:19",
        "width": null,
        "height": null,
        "issue": "[Errno 2] No such file or directory: 'data/test2.",
        "description": "Shop for Loewe Flamenco Clutch Bag in Ash Grey at FWRD. Free 2 day shipping and returns.",
        "domain": "fwrd.com",
        "source": "PARENT_URL",
        "brand": null,
        "slug": "loewe-flamenco-clutch-bag-in-ash-grey-fwrd-19623654081",
        "tags": "bag,clutch,farfetch,flamenco,fwrd,givenchy medium anti,loewe,loewe flamenco,loewe flamenco clutc,logo,owned,owned triangle,owned triangle logo,prada pre,pre,shoulder bag,tote,tote bag",
        "price_updated": null,
        "last_update": "2022-04-13 02:39:17",
        "currency": null,
        "price_old": null,
        "discount": null,
        "s3_url": null
    },
    {
        "page_id": "19623653771",
        "url": "http://fwrd.com/product-loewe-anagram-tote-mini-bag/LOEW-WY661/?d=Womens&itrownum=3&itcurrpage=1&itview=05",
        "canonical_url": "https://www.fwrd.com/product-loewe-anagram-tote-mini-bag-in-ecru-tan/LOEW-WY661/",
        "parent_url": "https://www.fwrd.com/category-bags/2df9df/?navsrc=hpbig2&featuredCodes=BOTT-WY752,BOTT-WY753,ALIA-WY49,TERX-WY142,OFFF-WY107,TERX-WY143,SLAU-WY1810,MI",
        "image_url": "https://is4.fwrdassets.com/images/p/fw/p/LOEW-WY661_V1.jpg",
        "price": "$1750",
        "name": "Loewe Anagram Tote Mini Bag in Ecru & Tan | FWRD",
        "product_confidence": "10",
        "crawled_time": "2022-04-13 02:38:09",
        "created_time": "2022-04-13 02:37:18",
        "width": null,
        "height": null,
        "issue": "[Errno 2] No such file or directory: 'data/test2.",
        "description": "Shop for Loewe Anagram Tote Mini Bag in Ecru & Tan at FWRD. Free 2 day shipping and returns.",
        "domain": "fwrd.com",
        "source": "PARENT_URL",
        "brand": null,
        "slug": "loewe-anagram-tote-mini-bag-in-ecru-tan-fwrd-19623653771",
        "tags": "bag,c\u00e9line,c\u00e9line pre,farfetch,handbag,louis,louis vuitton,louis vuitton 2002,louis vuitton 2004,louis vuitton pre,owned,owned macadam,owned pre,pre,speedy,tote,tote bag,vuitton",
        "price_updated": null,
        "last_update": "2022-04-13 02:39:38",
        "currency": null,
        "price_old": null,
        "discount": null,
        "s3_url": null
    },
    {
        "page_id": "19623557254",
        "url": "http://fwrd.com/product-agolde-tapered-baggy/AGOF-WJ111/?d=Womens&itrownum=2&itcurrpage=1&itview=05",
        "canonical_url": "https://www.fwrd.com/product-agolde-tapered-baggy-in-passenger/AGOF-WJ111/",
        "parent_url": "http://fwrd.com/new-arrivals-category-denim/0a97b2/?navsrc=left",
        "image_url": "https://is4.fwrdassets.com/images/p/fw/p/AGOF-WJ111_V1.jpg",
        "price": "$198",
        "name": "AGOLDE Tapered Baggy in Passenger | FWRD",
        "product_confidence": "10",
        "crawled_time": "2022-04-13 02:14:18",
        "created_time": "2022-04-13 02:13:51",
        "width": null,
        "height": null,
        "issue": "[Errno 2] No such file or directory: 'data/test2.",
        "description": "Shop for AGOLDE Tapered Baggy in Passenger at FWRD. Free 2 day shipping and returns.",
        "domain": "fwrd.com",
        "source": "PARENT_URL",
        "brand": null,
        "slug": "agolde-tapered-baggy-in-passenger-fwrd-19623557254",
        "tags": "agolde,blue,citizens humanity,denim,eb denim,eb denim low,frame le,fwrd,grlfrnd harlow high,grlfrnd melanie high,high,high rise,jean,light,low rise,revolve,rise,straight",
        "price_updated": null,
        "last_update": "2022-04-13 02:16:17",
        "currency": null,
        "price_old": null,
        "discount": null,
        "s3_url": null
    },
    {
        "page_id": "19623464474",
        "url": "http://fwrd.com/product-saint-laurent-toy-puffer-bag/SLAU-WY1902/?d=Womens&itrownum=1&itcurrpage=1&itview=05",
        "canonical_url": "https://www.fwrd.com/product-saint-laurent-toy-puffer-bag-in-basil-basil/SLAU-WY1902/",
        "parent_url": "http://fwrd.com/category-bags-crossbody-bags/f8c179/?navsrc=bags",
        "image_url": "https://is4.fwrdassets.com/images/p/fw/p/SLAU-WY1902_V1.jpg",
        "price": "$1790",
        "name": "Saint Laurent Toy Puffer Bag in Basil & Basil | FWRD",
        "product_confidence": "10",
        "crawled_time": "2022-04-13 01:58:26",
        "created_time": "2022-04-13 01:58:14",
        "width": null,
        "height": null,
        "issue": "[Errno 2] No such file or directory: 'data/test2.",
        "description": "Shop for Saint Laurent Toy Puffer Bag in Basil & Basil at FWRD. Free 2 day shipping and returns.",
        "domain": "fwrd.com",
        "source": "PARENT_URL",
        "brand": null,
        "slug": "saint-laurent-toy-puffer-bag-in-basil-basil-fwrd-19623464474",
        "tags": "bag,chain,chain bag,clutch,crossbody,crossbody bag,farfetch,fwrd,laurent,print,saint,saint laurent,saint laurent medium,saint laurent small,saint laurent toy,shoulder,shoulder bag,stella mccartney",
        "price_updated": null,
        "last_update": "2022-04-13 02:00:35",
        "currency": null,
        "price_old": null,
        "discount": null,
        "s3_url": null
    },
    // {
    //     "page_id": "19623464257",
    //     "url": "http://fwrd.com/product-saint-laurent-toy-puffer-bag/SLAU-WY1900/?d=Womens&itrownum=1&itcurrpage=1&itview=05",
    //     "canonical_url": "https://www.fwrd.com/product-saint-laurent-toy-puffer-bag-in-lemon-pie-lemon-pie/SLAU-WY1900/",
    //     "parent_url": "http://fwrd.com/category-bags-crossbody-bags/f8c179/?navsrc=bags",
    //     "image_url": "https://is4.fwrdassets.com/images/p/fw/p/SLAU-WY1900_V1.jpg",
    //     "price": "$1790",
    //     "name": "Saint Laurent Toy Puffer Bag in Lemon Pie & Lemon Pie | FWRD",
    //     "product_confidence": "10",
    //     "crawled_time": "2022-04-13 01:58:20",
    //     "created_time": "2022-04-13 01:58:14",
    //     "width": null,
    //     "height": null,
    //     "issue": "[Errno 2] No such file or directory: 'data/test2.",
    //     "description": "Shop for Saint Laurent Toy Puffer Bag in Lemon Pie & Lemon Pie at FWRD. Free 2 day shipping and returns.",
    //     "domain": "fwrd.com",
    //     "source": "PARENT_URL",
    //     "brand": null,
    //     "slug": "saint-laurent-toy-puffer-bag-in-lemon-pie-lemon-pie-fwrd-19623464257",
    //     "tags": "bag,chain bag,clutch,crossbody,crossbody bag,farfetch,fwrd,laurent,logo,pre,saint,saint laurent,saint laurent medium,saint laurent small,saint laurent toy,shoulder,shoulder bag,tote bag",
    //     "price_updated": null,
    //     "last_update": "2022-04-13 02:00:21",
    //     "currency": null,
    //     "price_old": null,
    //     "discount": null,
    //     "s3_url": null
    // },
    // {
    //     "page_id": "19623293243",
    //     "url": "https://au.publicdesire.com/products/summer-memories-beige-linen-strappy-stiletto-heels",
    //     "canonical_url": "https://au.publicdesire.com/products/summer-memories-beige-linen-strappy-stiletto-heels",
    //     "parent_url": "http://publicdesire.com/products/summer-memories-beige-linen-strappy-stiletto-heels",
    //     "image_url": "http://cdn.shopify.com/s/files/1/0359/5049/3835/products/0073_2b2a08f0-b844-4763-a000-b5fad9d83d02_1024x1024.jpg?v=1649771389",
    //     "price": "$63.00",
    //     "name": "Summer Memories Beige Linen Strappy Stiletto Heels",
    //     "product_confidence": "10",
    //     "crawled_time": "2022-04-13 01:22:10",
    //     "created_time": "2022-04-13 01:22:05",
    //     "width": null,
    //     "height": null,
    //     "issue": "[Errno 2] No such file or directory: 'data/test2.",
    //     "description": "Refresh your SS22 shoedrobe with Summer Memories. These stunning ecru linen strappy heels are this seasons must-have! We're styling with a classic little black dress and our fave mini handbag for a date night ready look. How will you style them up boo? Add Summer Memories to your dream stilettos collection today... Hee",
    //     "domain": "au.publicdesire.com",
    //     "source": "DOMAIN",
    //     "brand": null,
    //     "slug": "summer-memories-beige-linen-strappy-stiletto-heels-19623293243",
    //     "tags": "block,block heels,bow,bow square,bow square toe,heels,lace,mid,nude,patent,raffia square,square,square toe,square toe mid,strappy,toe,toe mid,wrap around diamante",
    //     "price_updated": null,
    //     "last_update": "2022-04-13 01:23:25",
    //     "currency": null,
    //     "price_old": null,
    //     "discount": null,
    //     "s3_url": null
    // },
    // {
    //     "page_id": "19623293242",
    //     "url": "https://us.publicdesire.com/products/summer-memories-beige-linen-strappy-stiletto-heels",
    //     "canonical_url": "https://us.publicdesire.com/products/summer-memories-beige-linen-strappy-stiletto-heels",
    //     "parent_url": "http://publicdesire.com/products/summer-memories-beige-linen-strappy-stiletto-heels",
    //     "image_url": "http://cdn.shopify.com/s/files/1/0361/8422/7971/products/0073_2b2a08f0-b844-4763-a000-b5fad9d83d02_1024x1024.jpg?v=1649770352",
    //     "price": "$44.99",
    //     "name": "Summer Memories Beige Linen Strappy Stiletto Heels",
    //     "product_confidence": "10",
    //     "crawled_time": "2022-04-13 01:22:10",
    //     "created_time": "2022-04-13 01:22:05",
    //     "width": null,
    //     "height": null,
    //     "issue": "[Errno 2] No such file or directory: 'data/test2.",
    //     "description": "Refresh your SS22 shoedrobe with Summer Memories. These stunning ecru linen strappy heels are this seasons must-have! We're styling with a classic little black dress and our fave mini handbag for a date night ready look. How will you style them up boo? Add Summer Memories to your dream stilettos collection today... Hee",
    //     "domain": "us.publicdesire.com",
    //     "source": "DOMAIN",
    //     "brand": null,
    //     "slug": "summer-memories-beige-linen-strappy-stiletto-heels-19623293242",
    //     "tags": "block,block heels,bow,bow square,bow square toe,heels,lace,mid,nude,patent,raffia square,square,square toe,square toe mid,strappy,toe,toe mid,wrap around diamante",
    //     "price_updated": null,
    //     "last_update": "2022-04-13 01:23:25",
    //     "currency": null,
    //     "price_old": null,
    //     "discount": null,
    //     "s3_url": null
    // },
    // {
    //     "page_id": "19623293241",
    //     "url": "https://eu.publicdesire.com/products/summer-memories-beige-linen-strappy-stiletto-heels",
    //     "canonical_url": "https://eu.publicdesire.com/products/summer-memories-beige-linen-strappy-stiletto-heels",
    //     "parent_url": "http://publicdesire.com/products/summer-memories-beige-linen-strappy-stiletto-heels",
    //     "image_url": "http://cdn.shopify.com/s/files/1/0342/1451/0651/products/0073_2b2a08f0-b844-4763-a000-b5fad9d83d02_1024x1024.jpg?v=1649771152",
    //     "price": "\u20ac3899",
    //     "name": "Summer Memories Beige Linen Strappy Stiletto Heels",
    //     "product_confidence": "10",
    //     "crawled_time": "2022-04-13 01:22:11",
    //     "created_time": "2022-04-13 01:22:05",
    //     "width": null,
    //     "height": null,
    //     "issue": "[Errno 2] No such file or directory: 'data/test2.",
    //     "description": "Refresh your SS22 shoedrobe with Summer Memories. These stunning ecru linen strappy heels are this seasons must-have! We're styling with a classic little black dress and our fave mini handbag for a date night ready look. How will you style them up boo? Add Summer Memories to your dream stilettos collection today... Hee",
    //     "domain": "eu.publicdesire.com",
    //     "source": "DOMAIN",
    //     "brand": null,
    //     "slug": "summer-memories-beige-linen-strappy-stiletto-heels-19623293241",
    //     "tags": "block,block heels,bow,bow square,bow square toe,heels,lace,mid,nude,patent,raffia square,square,square toe,square toe mid,strappy,toe,toe mid,wrap around diamante",
    //     "price_updated": null,
    //     "last_update": "2022-04-13 01:24:51",
    //     "currency": null,
    //     "price_old": null,
    //     "discount": null,
    //     "s3_url": null
    // },
    // {
    //     "page_id": "19623293237",
    //     "url": "https://eu.publicdesire.com/products/summer-memories-white-pu-strappy-stiletto-heels",
    //     "canonical_url": "https://eu.publicdesire.com/products/summer-memories-white-pu-strappy-stiletto-heels",
    //     "parent_url": "http://publicdesire.com/products/summer-memories-white-pu-strappy-stiletto-heels",
    //     "image_url": "http://cdn.shopify.com/s/files/1/0342/1451/0651/products/0063_c3603300-e67c-474b-8b8d-8068331f991f_1024x1024.jpg?v=1649771163",
    //     "price": "\u20ac3899",
    //     "name": "Summer Memories White PU Strappy Stiletto Heels",
    //     "product_confidence": "10",
    //     "crawled_time": "2022-04-13 01:22:20",
    //     "created_time": "2022-04-13 01:22:03",
    //     "width": null,
    //     "height": null,
    //     "issue": "[Errno 2] No such file or directory: 'data/test2.",
    //     "description": "Refresh your SS22 shoedrobe with Summer Memories. These stunning white linen strappy heels are this seasons must-have! We're styling with a classic little black dress and our fave mini handbag for a date night ready look. How will you style them up boo? Add Summer Memories to your dream stilettos collection today... He",
    //     "domain": "eu.publicdesire.com",
    //     "source": "DOMAIN",
    //     "brand": null,
    //     "slug": "summer-memories-white-pu-strappy-stiletto-heels-19623293237",
    //     "tags": "block,block heels,croc square,heels,lace,lace block,lace block heels,patent,patent lace,pu,slider,square,square toe lace,square toe strappy,strappy,toe,toe strappy,white",
    //     "price_updated": null,
    //     "last_update": "2022-04-13 01:25:23",
    //     "currency": null,
    //     "price_old": null,
    //     "discount": null,
    //     "s3_url": null
    // }
]